prompt
prompt Creating table ADR_EMAIL
prompt ========================
prompt
create table ADR_EMAIL
(
  ADR_EMAIL_EM_ADDR number(19) not null,
  RECIPCLASS        INTEGER,
  ADR_MAIL          NVARCHAR2(490),
  NOM_DEST          NVARCHAR2(490),
  constraint PK_ADR_EMAIL primary key (ADR_EMAIL_EM_ADDR)
) organization index ;


prompt
prompt Creating table BDG
prompt ==================
prompt
create table BDG
(
  BDG_EM_ADDR     number(19) not null,
  ID_BDG          INTEGER,
  B_CLE           NVARCHAR2(184),
  BDG_DESC        NVARCHAR2(120),
  BDG_PARENT_NODE RAW(16),
  constraint PK_BDG primary key (BDG_EM_ADDR)
) organization index ;



prompt
prompt Creating table BDG_TASK
prompt =======================
prompt
create table BDG_TASK
(
  BDG_TASK_EM_ADDR      number(19) not null,
  N0_BDG_TASK           INTEGER,
  OFTASK108_EM_ADDR     INTEGER,
  BDG109_EM_ADDR        INTEGER,
  OFTASK108_EM_ADDR_ORD INTEGER,
  BDG109_EM_ADDR_ORD    INTEGER,
  constraint PK_BDG_TASK primary key (BDG_TASK_EM_ADDR)
)organization index ;


prompt
prompt Creating table BGC
prompt ==================
prompt
create table BGC
(
  BGC_EM_ADDR       number(19) not null,
  NUM_BDG           INTEGER,
  ANNEE_DEBUT_BDG   INTEGER,
  PERIODE_DEBUT_BDG INTEGER,
  ANNEE_FIN_BDG     INTEGER,
  PERIODE_FIN_BDG   INTEGER,
  MODE_BDG          INTEGER,
  N0_SIMU           INTEGER,
  DATE_MODIFY_BGC   FLOAT,
  BDG31_EM_ADDR     INTEGER,
  EXO43_EM_ADDR     INTEGER,
  BDG31_EM_ADDR_ORD INTEGER,
  EXO43_EM_ADDR_ORD INTEGER,
  constraint PK_BGC primary key (BGC_EM_ADDR)
)organization index ;


prompt
prompt Creating table BUD
prompt ==================
prompt
create table BUD
(
  BUD_EM_ADDR       number(19) not null,
  ANNEE_BDG         INTEGER,
  M_BDG_1           FLOAT,
  M_BDG_2           FLOAT,
  M_BDG_3           FLOAT,
  M_BDG_4           FLOAT,
  M_BDG_5           FLOAT,
  M_BDG_6           FLOAT,
  M_BDG_7           FLOAT,
  M_BDG_8           FLOAT,
  M_BDG_9           FLOAT,
  M_BDG_10          FLOAT,
  M_BDG_11          FLOAT,
  M_BDG_12          FLOAT,
  M_BDG_13          FLOAT,
  M_BDG_14          FLOAT,
  BGC32_EM_ADDR     INTEGER,
  BGC32_EM_ADDR_ORD INTEGER,
  constraint PK_BUD primary key (BUD_EM_ADDR)
)organization index ;


prompt
prompt Creating table CDT
prompt ==================
prompt
create table CDT
(
  CDT_EM_ADDR       number(19) not null,
  N0_CDT            INTEGER,
  RCD_CDT           INTEGER,
  OPERANT           INTEGER,
  N0_VAL_CDT        INTEGER,
  ADR_CDT           RAW(16),
  SEL11_EM_ADDR     INTEGER,
  PRV12_EM_ADDR     INTEGER,
  SEL11_EM_ADDR_ORD INTEGER,
  PRV12_EM_ADDR_ORD INTEGER,
  constraint PK_CDT primary key (CDT_EM_ADDR)
)organization index ;





prompt
prompt Creating table CONTENU_ETAT
prompt ===========================
prompt
create table CONTENU_ETAT
(
  CONTENU_ETAT_EM_ADDR number(19) not null,
  N0_FORM              INTEGER,
  CONTENU_ETAT_SIZE    INTEGER,
  CONTENU_FORM         BLOB,
  FORM63_EM_ADDR       INTEGER,
  FORM63_EM_ADDR_ORD   INTEGER,
  constraint PK_CONTENU_ETAT primary key (CONTENU_ETAT_EM_ADDR)
)
organization index ;


prompt
prompt Creating table CRTSERIE
prompt =======================
prompt
create table CRTSERIE
(
  CRTSERIE_EM_ADDR number(19) not null,
  ID_CRT_SERIE     INTEGER,
  NUM_CRT_SERIE    INTEGER,
  VAL_CRT_SERIE    NVARCHAR2(60),
  LIB_CRT_SERIE    NVARCHAR2(120),
  MODE_STATUS      INTEGER,
  ECLAT_STATUS     INTEGER,
  PRIORITE_STATUS  INTEGER,
  COLOR_STATUS     INTEGER,
  CREATE_PVT       INTEGER,
  AFFICHE_PLANNING INTEGER,
  constraint PK_CRTSERIE primary key (CRTSERIE_EM_ADDR)
)
organization index ;


prompt
prompt Creating table DETAILREMARK
prompt ===========================
prompt
create table DETAILREMARK
(
  DETAILREMARK_EM_ADDR       number(19) not null,
  N0PAGE_DETAILREMARK        INTEGER,
  DETAIL_REMARK              NVARCHAR2(1002),
  DETAILSERIE115_EM_ADDR     INTEGER,
  DETAILSERIE115_EM_ADDR_ORD INTEGER,
  constraint PK_DETAILREMARK primary key (DETAILREMARK_EM_ADDR)
)
organization index ;

prompt
prompt Creating table DETAILSERIE
prompt ==========================
prompt
create table DETAILSERIE
(
  DETAILSERIE_EM_ADDR        number(19) not null,
  TYPE_DETAILSERIE           INTEGER,
  ID_COMMANDE                NVARCHAR2(60),
  ID_CLIENT                  NVARCHAR2(60),
  QTE_COMMANDE               FLOAT,
  DATE_EXPED_DEMAND          FLOAT,
  DATE_DLUO                  FLOAT,
  DATE_PROD                  FLOAT,
  QTE_LIVRE                  FLOAT,
  DATE_LIVRAISON             FLOAT,
  DATE_PROD_INIT             FLOAT,
  QTE_RELIQUAT               FLOAT,
  STATUT                     INTEGER,
  DATE_MODIFY_SERIEDETAIL    FLOAT,
  USER_MODIFY_SERIEDETAIL    NVARCHAR2(60),
  DETAILSERIE_SUP            RAW(20),
  DETAILSERIE_DATA           BLOB,
  DETAILTYPE113_EM_ADDR      INTEGER,
  DETAILSERIE114_EM_ADDR     INTEGER,
  DETAILTYPE113_EM_ADDR_ORD  INTEGER,
  DETAILSERIE114_EM_ADDR_ORD INTEGER,
  constraint PK_DETAILSERIE primary key (DETAILSERIE_EM_ADDR)
)
organization index ;


prompt
prompt Creating table DETAILTYPE
prompt =========================
prompt
create table DETAILTYPE
(
  DETAILTYPE_EM_ADDR number(19) not null,
  DETAIL_TYPE        INTEGER,
  BDG112_EM_ADDR     INTEGER,
  BDG112_EM_ADDR_ORD INTEGER,
  constraint PK_DETAILTYPE primary key (DETAILTYPE_EM_ADDR)
)
organization index ;


prompt
prompt Creating table DETAIL_SEQUENCE
prompt ==============================
prompt
create table DETAIL_SEQUENCE
(
  DETAIL_SEQUENCE_EM_ADDR        number(19) not null,
  PLANIF_DATE                    FLOAT,
  PROD_QTY                       INTEGER,
  LINK_DEPTH                     INTEGER,
  DETAIL_SEQ_ID                  INTEGER,
  LINK_TYPE                      INTEGER,
  SUP_DETAIL_SEQ                 RAW(150),
  TYPE_SEQUENCE135_EM_ADDR       INTEGER,
  DETAIL_SEQUENCE136_EM_ADDR     INTEGER,
  DETAIL_SEQUENCE137_EM_ADDR     INTEGER,
  TYPE_SEQUENCE135_EM_ADDR_ORD   INTEGER,
  DETAIL_SEQUENCE136_EM_ADDR_ORD INTEGER,
  DETAIL_SEQUENCE137_EM_ADDR_ORD INTEGER,
  constraint PK_DETAIL_SEQUENCE primary key (DETAIL_SEQUENCE_EM_ADDR)
)
organization index ;


prompt
prompt Creating table DIS
prompt ==================
prompt
create table DIS
(
  DIS_EM_ADDR       number(19) not null,
  D_CLE             NVARCHAR2(60),
  D_DESC            NVARCHAR2(120),
  D_DESC_COURT      NVARCHAR2(60),
  SUP_DIS           RAW(12),
  USER_CREATE_DIS   NVARCHAR2(60),
  DATE_CREATE_DIS   FLOAT,
  USER_MODIFY_DIS   NVARCHAR2(60),
  DATE_MODIFY_DIS   FLOAT,
  STATUS_DIS        INTEGER,
  DIS2_EM_ADDR      INTEGER,
  RMS40_EM_ADDR     INTEGER,
  DIS2_EM_ADDR_ORD  INTEGER,
  RMS40_EM_ADDR_ORD INTEGER,
  constraint PK_DIS primary key (DIS_EM_ADDR)
)
organization index ;


prompt
prompt Creating table DON
prompt ==================
prompt
create table DON
(
  DON_EM_ADDR       number(19) not null,
  ANNEE             INTEGER,
  M_1               FLOAT,
  M_2               FLOAT,
  M_3               FLOAT,
  M_4               FLOAT,
  M_5               FLOAT,
  M_6               FLOAT,
  M_7               FLOAT,
  M_8               FLOAT,
  M_9               FLOAT,
  M_10              FLOAT,
  M_11              FLOAT,
  M_12              FLOAT,
  M_13              FLOAT,
  M_14              FLOAT,
  RPD18_EM_ADDR     INTEGER,
  RPD18_EM_ADDR_ORD INTEGER,
  constraint PK_DON primary key (DON_EM_ADDR)
)
organization index ;


prompt
prompt Creating table DON_BUDGET
prompt =========================
prompt
create table DON_BUDGET
(
  DON_BUDGET_EM_ADDR         number(19) not null,
  ANNEE_BUDGET               INTEGER,
  M_DON_BUDGET_1             FLOAT,
  M_DON_BUDGET_2             FLOAT,
  M_DON_BUDGET_3             FLOAT,
  M_DON_BUDGET_4             FLOAT,
  M_DON_BUDGET_5             FLOAT,
  M_DON_BUDGET_6             FLOAT,
  M_DON_BUDGET_7             FLOAT,
  M_DON_BUDGET_8             FLOAT,
  M_DON_BUDGET_9             FLOAT,
  M_DON_BUDGET_10            FLOAT,
  M_DON_BUDGET_11            FLOAT,
  M_DON_BUDGET_12            FLOAT,
  M_DON_BUDGET_13            FLOAT,
  M_DON_BUDGET_14            FLOAT,
  SERIE_BUDGET71_EM_ADDR     INTEGER,
  SERIE_BUDGET71_EM_ADDR_ORD INTEGER,
  constraint PK_DON_BUDGET primary key (DON_BUDGET_EM_ADDR)
)
organization index ;


prompt
prompt Creating table DON_NMC
prompt ======================
prompt
create table DON_NMC
(
  DON_NMC_EM_ADDR          number(19) not null,
  ANNEE_NMC                INTEGER,
  M_DON_NMC_1              FLOAT,
  M_DON_NMC_2              FLOAT,
  M_DON_NMC_3              FLOAT,
  M_DON_NMC_4              FLOAT,
  M_DON_NMC_5              FLOAT,
  M_DON_NMC_6              FLOAT,
  M_DON_NMC_7              FLOAT,
  M_DON_NMC_8              FLOAT,
  M_DON_NMC_9              FLOAT,
  M_DON_NMC_10             FLOAT,
  M_DON_NMC_11             FLOAT,
  M_DON_NMC_12             FLOAT,
  M_DON_NMC_13             FLOAT,
  M_DON_NMC_14             FLOAT,
  SERIE_NMC117_EM_ADDR     INTEGER,
  SERIE_NMC117_EM_ADDR_ORD INTEGER,
  constraint PK_DON_NMC primary key (DON_NMC_EM_ADDR)
)
organization index ;


prompt
prompt Creating table DON_PVT
prompt ======================
prompt
create table DON_PVT
(
  DON_PVT_EM_ADDR         number(19) not null,
  ANNEE_PVT               INTEGER,
  M_DON_PVT_1             FLOAT,
  M_DON_PVT_2             FLOAT,
  M_DON_PVT_3             FLOAT,
  M_DON_PVT_4             FLOAT,
  M_DON_PVT_5             FLOAT,
  M_DON_PVT_6             FLOAT,
  M_DON_PVT_7             FLOAT,
  M_DON_PVT_8             FLOAT,
  M_DON_PVT_9             FLOAT,
  M_DON_PVT_10            FLOAT,
  M_DON_PVT_11            FLOAT,
  M_DON_PVT_12            FLOAT,
  M_DON_PVT_13            FLOAT,
  M_DON_PVT_14            FLOAT,
  SERIE_PVT20_EM_ADDR     INTEGER,
  SERIE_PVT20_EM_ADDR_ORD INTEGER,
  constraint PK_DON_PVT primary key (DON_PVT_EM_ADDR)
)
organization index ;


prompt
prompt Creating table DON_SEL
prompt ======================
prompt
create table DON_SEL
(
  DON_SEL_EM_ADDR         number(19) not null,
  ANNEE_SEL               INTEGER,
  M_DON_SEL_1             FLOAT,
  M_DON_SEL_2             FLOAT,
  M_DON_SEL_3             FLOAT,
  M_DON_SEL_4             FLOAT,
  M_DON_SEL_5             FLOAT,
  M_DON_SEL_6             FLOAT,
  M_DON_SEL_7             FLOAT,
  M_DON_SEL_8             FLOAT,
  M_DON_SEL_9             FLOAT,
  M_DON_SEL_10            FLOAT,
  M_DON_SEL_11            FLOAT,
  M_DON_SEL_12            FLOAT,
  M_DON_SEL_13            FLOAT,
  M_DON_SEL_14            FLOAT,
  SERIE_SEL24_EM_ADDR     INTEGER,
  SERIE_SEL24_EM_ADDR_ORD INTEGER,
  constraint PK_DON_SEL primary key (DON_SEL_EM_ADDR)
)
organization index ;


prompt
prompt Creating table DON_SUPPLIER
prompt ===========================
prompt
create table DON_SUPPLIER
(
  DON_SUPPLIER_EM_ADDR           number(19) not null,
  ANNEE_SUPPLIER                 INTEGER,
  M_DON_SUPPLIER_1               FLOAT,
  M_DON_SUPPLIER_2               FLOAT,
  M_DON_SUPPLIER_3               FLOAT,
  M_DON_SUPPLIER_4               FLOAT,
  M_DON_SUPPLIER_5               FLOAT,
  M_DON_SUPPLIER_6               FLOAT,
  M_DON_SUPPLIER_7               FLOAT,
  M_DON_SUPPLIER_8               FLOAT,
  M_DON_SUPPLIER_9               FLOAT,
  M_DON_SUPPLIER_10              FLOAT,
  M_DON_SUPPLIER_11              FLOAT,
  M_DON_SUPPLIER_12              FLOAT,
  M_DON_SUPPLIER_13              FLOAT,
  M_DON_SUPPLIER_14              FLOAT,
  SERIE_SUPPLIER2119_EM_ADDR     INTEGER,
  SERIE_SUPPLIER2119_EM_ADDR_ORD INTEGER,
  constraint PK_DON_SUPPLIER primary key (DON_SUPPLIER_EM_ADDR)
)
organization index ;


prompt
prompt Creating table DVS
prompt ==================
prompt
create table DVS
(
  DVS_EM_ADDR     number(19) not null,
  DVS_FIELD       RAW(18),
  DVS_CLE         NVARCHAR2(60),
  DVS_DESC        NVARCHAR2(120),
  USER_CREATE_DVS NVARCHAR2(60),
  DATE_CREATE_DVS FLOAT,
  USER_MODIFY_DVS NVARCHAR2(60),
  DATE_MODIFY_DVS FLOAT,
  constraint PK_DVS primary key (DVS_EM_ADDR)
)
organization index ;


prompt
prompt Creating table EXO
prompt ==================
prompt
create table EXO
(
  EXO_EM_ADDR     number(19) not null,
  EXO_CLE         NVARCHAR2(60),
  EXO_DESC        NVARCHAR2(120),
  EXO_DURE        INTEGER,
  EXO_TYPE        RAW(52),
  USER_CREATE_EXO NVARCHAR2(60),
  DATE_CREATE_EXO FLOAT,
  USER_MODIFY_EXO NVARCHAR2(60),
  DATE_MODIFY_EXO FLOAT,
  constraint PK_EXO primary key (EXO_EM_ADDR)
)
organization index ;

prompt
prompt Creating table FAM
prompt ==================
prompt
create table FAM
(
  FAM_EM_ADDR       number(19) not null,
  ID_FAM            INTEGER,
  F_CLE             NVARCHAR2(60),
  F_DESC            NVARCHAR2(120),
  F_DESC_COURT      NVARCHAR2(60),
  PRIX_1            FLOAT,
  PRIX_2            FLOAT,
  PRIX_3            FLOAT,
  PRIX_4            FLOAT,
  PRIX_5            FLOAT,
  PRIX_6            FLOAT,
  PRIX_7            FLOAT,
  PRIX_8            FLOAT,
  PRIX_9            FLOAT,
  PRIX_10           FLOAT,
  UNITE_1           FLOAT,
  UNITE_2           FLOAT,
  UNITE_3           FLOAT,
  UNITE_4           FLOAT,
  UNITE_5           FLOAT,
  UNITE_6           FLOAT,
  UNITE_7           FLOAT,
  UNITE_8           FLOAT,
  UNITE_9           FLOAT,
  UNITE_10          FLOAT,
  SUP_FAM           RAW(34),
  USER_CREATE_FAM   NVARCHAR2(60),
  DATE_CREATE_FAM   FLOAT,
  USER_MODIFY_FAM   NVARCHAR2(60),
  DATE_MODIFY_FAM   FLOAT,
  FAM0_EM_ADDR      INTEGER,
  FAM37_EM_ADDR     INTEGER,
  NMC1_EM_ADDR      INTEGER,
  FAM0_EM_ADDR_ORD  INTEGER,
  FAM37_EM_ADDR_ORD INTEGER,
  NMC1_EM_ADDR_ORD  INTEGER,
  constraint PK_FAM primary key (FAM_EM_ADDR)
)
organization index ;


prompt
prompt Creating table FAMTRF
prompt =====================
prompt
create table FAMTRF
(
  FAMTRF_EM_ADDR    number(19) not null,
  NUM_TRF           INTEGER,
  FAM33_EM_ADDR     INTEGER,
  TRF34_EM_ADDR     INTEGER,
  FAM33_EM_ADDR_ORD INTEGER,
  TRF34_EM_ADDR_ORD INTEGER,
  constraint PK_FAMTRF primary key (FAMTRF_EM_ADDR)
)
organization index ;

prompt
prompt Creating table FORM
prompt ===================
prompt
create table FORM
(
  FORM_EM_ADDR             number(19) not null,
  ID_ETAT                  INTEGER,
  CLE_ETAT                 NVARCHAR2(60),
  ETAT_DESC                NVARCHAR2(120),
  USER_CREATE_FORM         NVARCHAR2(60),
  DATE_CREATE_FORM         FLOAT,
  USER_MODIFY_FORM         NVARCHAR2(60),
  DATE_MODIFY_FORM         FLOAT,
  DATE_EXPIRE_FORM         FLOAT,
  DATE_USED_FROM_FORM      FLOAT,
  DATE_USED_UNTIL_FORM     FLOAT,
  DATE_MODIFIED_FROM_FORM  FLOAT,
  DATE_MODIFIED_UNTIL_FORM FLOAT,
  USER_LAST_USED           NVARCHAR2(60),
  DATE_LAST_USED_FORM      FLOAT,
  FORM_CONTENU_SIZE        INTEGER,
  PROFIL45_EM_ADDR         INTEGER,
  FORM46_EM_ADDR           INTEGER,
  PRV64_EM_ADDR            INTEGER,
  SEL65_EM_ADDR            INTEGER,
  PRV133_EM_ADDR           INTEGER,
  PROFIL45_EM_ADDR_ORD     INTEGER,
  FORM46_EM_ADDR_ORD       INTEGER,
  PRV64_EM_ADDR_ORD        INTEGER,
  SEL65_EM_ADDR_ORD        INTEGER,
  PRV133_EM_ADDR_ORD       INTEGER,
  constraint PK_FORM primary key (FORM_EM_ADDR)
)
organization index ;


prompt
prompt Creating table FORM_CRTSERIE
prompt ============================
prompt
create table FORM_CRTSERIE
(
  FORM_CRTSERIE_EM_ADDR   number(19) not null,
  N0VERSION_FORM_CRTSERIE INTEGER,
  PARAM_FORM_CRTSERIE_1   INTEGER,
  PARAM_FORM_CRTSERIE_2   INTEGER,
  PARAM_FORM_CRTSERIE_3   INTEGER,
  PARAM_FORM_CRTSERIE_4   INTEGER,
  PARAM_FORM_CRTSERIE_5   INTEGER,
  PARAM_FORM_CRTSERIE_6   INTEGER,
  PARAM_FORM_CRTSERIE_7   INTEGER,
  PARAM_FORM_CRTSERIE_8   INTEGER,
  PARAM_FORM_CRTSERIE_9   INTEGER,
  PARAM_FORM_CRTSERIE_10  INTEGER,
  PARAM_FORM_CRTSERIE_11  INTEGER,
  PARAM_FORM_CRTSERIE_12  INTEGER,
  PARAM_FORM_CRTSERIE_13  INTEGER,
  PARAM_FORM_CRTSERIE_14  INTEGER,
  PARAM_FORM_CRTSERIE_15  INTEGER,
  PARAM_FORM_CRTSERIE_16  INTEGER,
  PARAM_FORM_CRTSERIE_17  INTEGER,
  PARAM_FORM_CRTSERIE_18  INTEGER,
  PARAM_FORM_CRTSERIE_19  INTEGER,
  PARAM_FORM_CRTSERIE_20  INTEGER,
  FORM102_EM_ADDR         INTEGER,
  CRTSERIE103_EM_ADDR     INTEGER,
  FORM102_EM_ADDR_ORD     INTEGER,
  CRTSERIE103_EM_ADDR_ORD INTEGER,
  constraint PK_FORM_CRTSERIE primary key (FORM_CRTSERIE_EM_ADDR)
)
organization index ;

prompt
prompt Creating table FORM_VCT
prompt =======================
prompt
create table FORM_VCT
(
  FORM_VCT_EM_ADDR    number(19) not null,
  PARAM_FORM_VCT_1    INTEGER,
  PARAM_FORM_VCT_2    INTEGER,
  PARAM_FORM_VCT_3    INTEGER,
  PARAM_FORM_VCT_4    INTEGER,
  PARAM_FORM_VCT_5    INTEGER,
  PARAM_FORM_VCT_6    INTEGER,
  PARAM_FORM_VCT_7    INTEGER,
  PARAM_FORM_VCT_8    INTEGER,
  PARAM_FORM_VCT_9    INTEGER,
  PARAM_FORM_VCT_10   INTEGER,
  PARAM_FORM_VCT_11   INTEGER,
  PARAM_FORM_VCT_12   INTEGER,
  PARAM_FORM_VCT_13   INTEGER,
  PARAM_FORM_VCT_14   INTEGER,
  PARAM_FORM_VCT_15   INTEGER,
  PARAM_FORM_VCT_16   INTEGER,
  PARAM_FORM_VCT_17   INTEGER,
  PARAM_FORM_VCT_18   INTEGER,
  PARAM_FORM_VCT_19   INTEGER,
  PARAM_FORM_VCT_20   INTEGER,
  FORM100_EM_ADDR     INTEGER,
  VCT101_EM_ADDR      INTEGER,
  FORM100_EM_ADDR_ORD INTEGER,
  VCT101_EM_ADDR_ORD  INTEGER,
  constraint PK_FORM_VCT primary key (FORM_VCT_EM_ADDR)
)
organization index ;

prompt
prompt Creating table GEO
prompt ==================
prompt
create table GEO
(
  GEO_EM_ADDR      number(19) not null,
  G_CLE            NVARCHAR2(60),
  G_DESC           NVARCHAR2(120),
  G_DESC_COURT     NVARCHAR2(60),
  SUP_GEO          RAW(12),
  USER_CREATE_GEO  NVARCHAR2(60),
  DATE_CREATE_GEO  FLOAT,
  USER_MODIFY_GEO  NVARCHAR2(60),
  DATE_MODIFY_GEO  FLOAT,
  GEO1_EM_ADDR     INTEGER,
  GEO1_EM_ADDR_ORD INTEGER,
  constraint PK_GEO primary key (GEO_EM_ADDR)
)
organization index ;

prompt
prompt Creating table GEODVS
prompt =====================
prompt
create table GEODVS
(
  GEODVS_EM_ADDR    number(19) not null,
  N0_DVS            INTEGER,
  DVS38_EM_ADDR     INTEGER,
  GEO39_EM_ADDR     INTEGER,
  DVS38_EM_ADDR_ORD INTEGER,
  GEO39_EM_ADDR_ORD INTEGER,
  constraint PK_GEODVS primary key (GEODVS_EM_ADDR)
)
organization index ;


prompt
prompt Creating table IST
prompt ==================
prompt
create table IST
(
  IST_EM_ADDR     number(19) not null,
  IST_CLE         NVARCHAR2(60),
  IST_DATA_SIZE   INTEGER,
  USER_CREATE_IST NVARCHAR2(60),
  DATE_CREATE_IST FLOAT,
  USER_MODIFY_IST NVARCHAR2(60),
  DATE_MODIFY_IST FLOAT,
  constraint PK_IST primary key (IST_EM_ADDR)
)
organization index ;

prompt
prompt Creating table IST_CRTSERIE
prompt ===========================
prompt
create table IST_CRTSERIE
(
  IST_CRTSERIE_EM_ADDR   number(19) not null,
  N0_IST_CRTSERIE        INTEGER,
  IST83_EM_ADDR          INTEGER,
  CRTSERIE90_EM_ADDR     INTEGER,
  IST83_EM_ADDR_ORD      INTEGER,
  CRTSERIE90_EM_ADDR_ORD INTEGER,
  constraint PK_IST_CRTSERIE primary key (IST_CRTSERIE_EM_ADDR)
)
organization index ;

prompt
prompt Creating table IST_DIS
prompt ======================
prompt
create table IST_DIS
(
  IST_DIS_EM_ADDR   number(19) not null,
  N0_IST_DIS        INTEGER,
  IST84_EM_ADDR     INTEGER,
  DIS87_EM_ADDR     INTEGER,
  IST84_EM_ADDR_ORD INTEGER,
  DIS87_EM_ADDR_ORD INTEGER,
  constraint PK_IST_DIS primary key (IST_DIS_EM_ADDR)
)
organization index ;


prompt
prompt Creating table IST_FAM
prompt ======================
prompt
create table IST_FAM
(
  IST_FAM_EM_ADDR   number(19) not null,
  N0_IST_FAM        INTEGER,
  IST86_EM_ADDR     INTEGER,
  FAM89_EM_ADDR     INTEGER,
  IST86_EM_ADDR_ORD INTEGER,
  FAM89_EM_ADDR_ORD INTEGER,
  constraint PK_IST_FAM primary key (IST_FAM_EM_ADDR)
)
organization index ;


prompt
prompt Creating table IST_GEO
prompt ======================
prompt
create table IST_GEO
(
  IST_GEO_EM_ADDR   number(19) not null,
  N0_IST_GEO        INTEGER,
  IST85_EM_ADDR     INTEGER,
  GEO88_EM_ADDR     INTEGER,
  IST85_EM_ADDR_ORD INTEGER,
  GEO88_EM_ADDR_ORD INTEGER,
  constraint PK_IST_GEO primary key (IST_GEO_EM_ADDR)
)
organization index ;


prompt
prompt Creating table IST_PARAM
prompt ========================
prompt
create table IST_PARAM
(
  IST_PARAM_EM_ADDR          number(19) not null,
  N0_IST_PARAM               INTEGER,
  IST82_EM_ADDR              INTEGER,
  OPTION_PARAM91_EM_ADDR     INTEGER,
  IST82_EM_ADDR_ORD          INTEGER,
  OPTION_PARAM91_EM_ADDR_ORD INTEGER,
  constraint PK_IST_PARAM primary key (IST_PARAM_EM_ADDR)
)
organization index ;


prompt
prompt Creating table IST_PRV
prompt ======================
prompt
create table IST_PRV
(
  IST_PRV_EM_ADDR   number(19) not null,
  N0_IST_PRV        INTEGER,
  IST76_EM_ADDR     INTEGER,
  PRV77_EM_ADDR     INTEGER,
  IST76_EM_ADDR_ORD INTEGER,
  PRV77_EM_ADDR_ORD INTEGER,
  constraint PK_IST_PRV primary key (IST_PRV_EM_ADDR)
)
organization index ;


prompt
prompt Creating table IST_SCL
prompt ======================
prompt
create table IST_SCL
(
  IST_SCL_EM_ADDR   number(19) not null,
  N0_IST_SCL        INTEGER,
  IST78_EM_ADDR     INTEGER,
  SCL79_EM_ADDR     INTEGER,
  IST78_EM_ADDR_ORD INTEGER,
  SCL79_EM_ADDR_ORD INTEGER,
  constraint PK_IST_SCL primary key (IST_SCL_EM_ADDR)
)
organization index ;

prompt
prompt Creating table IST_SEL
prompt ======================
prompt
create table IST_SEL
(
  IST_SEL_EM_ADDR   number(19) not null,
  N0_IST_SEL        INTEGER,
  IST73_EM_ADDR     INTEGER,
  SEL75_EM_ADDR     INTEGER,
  IST73_EM_ADDR_ORD INTEGER,
  SEL75_EM_ADDR_ORD INTEGER,
  constraint PK_IST_SEL primary key (IST_SEL_EM_ADDR)
)
organization index ;

prompt
prompt Creating table IST_VCT
prompt ======================
prompt
create table IST_VCT
(
  IST_VCT_EM_ADDR   number(19) not null,
  N0_IST_VCT        INTEGER,
  IST80_EM_ADDR     INTEGER,
  VCT81_EM_ADDR     INTEGER,
  IST80_EM_ADDR_ORD INTEGER,
  VCT81_EM_ADDR_ORD INTEGER,
  constraint PK_IST_VCT primary key (IST_VCT_EM_ADDR)
)
organization index ;

prompt
prompt Creating table IST_XMLDATA
prompt ==========================
prompt
create table IST_XMLDATA
(
  IST_XMLDATA_EM_ADDR number(19) not null,
  N0_IST_XMLDATA      INTEGER,
  IST_XMLDATA_SIZE    INTEGER,
  CONTENU_IST_XMLDATA BLOB,
  IST74_EM_ADDR       INTEGER,
  IST74_EM_ADDR_ORD   INTEGER,
  constraint PK_IST_XMLDATA primary key (IST_XMLDATA_EM_ADDR)
)
organization index ;

prompt
prompt Creating table LANGUE
prompt =====================
prompt
create table LANGUE
(
  LANGUE_EM_ADDR number(19) not null,
  CLE_LANGUE     NVARCHAR2(60),
  LIB_LANGUE     NVARCHAR2(120),
  constraint PK_LANGUE primary key (LANGUE_EM_ADDR)
)
organization index ;


prompt
prompt Creating table LIB_FAM_LANGUE
prompt =============================
prompt
create table LIB_FAM_LANGUE
(
  LIB_FAM_LANGUE_EM_ADDR number(19) not null,
  DESC_FAM_LANGUE        NVARCHAR2(120),
  DESC_FAM_LANGUE_COURT  NVARCHAR2(60),
  LANGUE61_EM_ADDR       INTEGER,
  FAM62_EM_ADDR          INTEGER,
  LANGUE61_EM_ADDR_ORD   INTEGER,
  FAM62_EM_ADDR_ORD      INTEGER,
  constraint PK_LIB_FAM_LANGUE primary key (LIB_FAM_LANGUE_EM_ADDR)
)
organization index ;

prompt
prompt Creating table LICENSE
prompt ======================
prompt
create table LICENSE
(
  LICENSE_EM_ADDR number(19) not null,
  LICENSE_ID      NVARCHAR2(236),
  constraint PK_LICENSE primary key (LICENSE_EM_ADDR)
)
organization index ;


prompt
prompt Creating table LIEN_ETAT_MAIL
prompt =============================
prompt
create table LIEN_ETAT_MAIL
(
  LIEN_ETAT_MAIL_EM_ADDR  number(19) not null,
  DATE_MODIF_DIFFUSION    INTEGER,
  MAIL_INFO49_EM_ADDR     INTEGER,
  ADR_EMAIL50_EM_ADDR     INTEGER,
  MAIL_INFO49_EM_ADDR_ORD INTEGER,
  ADR_EMAIL50_EM_ADDR_ORD INTEGER,
  constraint PK_LIEN_ETAT_MAIL primary key (LIEN_ETAT_MAIL_EM_ADDR)
)
organization index ;


prompt
prompt Creating table LOGSESSION
prompt =========================
prompt
create table LOGSESSION
(
  LOGSESSION_EM_ADDR number(19) not null,
  LOGID              INTEGER,
  LICENSE_KEY_PATH   NVARCHAR2(1022),
  DBUSERID           NVARCHAR2(254),
  USERNAME           NVARCHAR2(254),
  NB_USER_CONNECTED  INTEGER,
  SESSION_START_DATE FLOAT,
  SESSION_DURATION   FLOAT,
  LOG_DATA           BLOB,
   constraint PK_LOGSESSION primary key (LOGSESSION_EM_ADDR)
)
organization index 
PCTTHRESHOLD 20
overflow 
INCLUDING LOG_DATA;


prompt
prompt Creating table MAIL_INFO
prompt ========================
prompt
create table MAIL_INFO
(
  MAIL_INFO_EM_ADDR number(19) not null,
  ID_TEMPLATE       INTEGER,
  CLE_TEMPLATE      NVARCHAR2(60),
  SUJET             NVARCHAR2(510),
  ATTACHE           NVARCHAR2(1022),
  LPSZNOTETEXT      NVARCHAR2(1022),
  BNOTIFYREQUEST    INTEGER,
  BSENDDIRECTLY     INTEGER,
  LPSZPROFILE       NVARCHAR2(254),
  SUP_MAIL_INFO_1   INTEGER,
  SUP_MAIL_INFO_2   INTEGER,
  SUP_MAIL_INFO_3   INTEGER,
  SUP_MAIL_INFO_4   INTEGER,
  SUP_MAIL_INFO_5   INTEGER,
  SUP_MAIL_INFO_6   INTEGER,
  SUP_MAIL_INFO_7   INTEGER,
  SUP_MAIL_INFO_8   INTEGER,
  SUP_MAIL_INFO_9   INTEGER,
  SUP_MAIL_INFO_10  INTEGER,
  SUP_MAIL_INFO_11  INTEGER,
  SUP_MAIL_INFO_12  INTEGER,
  SUP_MAIL_INFO_13  INTEGER,
  SUP_MAIL_INFO_14  INTEGER,
  SUP_MAIL_INFO_15  INTEGER,
  SUP_MAIL_INFO_16  INTEGER,
  SUP_MAIL_INFO_17  INTEGER,
  SUP_MAIL_INFO_18  INTEGER,
  SUP_MAIL_INFO_19  INTEGER,
  SUP_MAIL_INFO_20  INTEGER,
  SUP_MAIL_INFO_21  INTEGER,
  SUP_MAIL_INFO_22  INTEGER,
  SUP_MAIL_INFO_23  INTEGER,
  SUP_MAIL_INFO_24  INTEGER,
  SUP_MAIL_INFO_25  INTEGER,
  SUP_MAIL_INFO_26  INTEGER,
  SUP_MAIL_INFO_27  INTEGER,
  SUP_MAIL_INFO_28  INTEGER,
  SUP_MAIL_INFO_29  INTEGER,
  SUP_MAIL_INFO_30  INTEGER,
  SUP_MAIL_INFO_31  INTEGER,
  SUP_MAIL_INFO_32  INTEGER,
  SUP_MAIL_INFO_33  INTEGER,
  SUP_MAIL_INFO_34  INTEGER,
  SUP_MAIL_INFO_35  INTEGER,
  SUP_MAIL_INFO_36  INTEGER,
  SUP_MAIL_INFO_37  INTEGER,
  SUP_MAIL_INFO_38  INTEGER,
  SUP_MAIL_INFO_39  INTEGER,
  SUP_MAIL_INFO_40  INTEGER,
  SUP_MAIL_INFO_41  INTEGER,
  SUP_MAIL_INFO_42  INTEGER,
  SUP_MAIL_INFO_43  INTEGER,
  SUP_MAIL_INFO_44  INTEGER,
  SUP_MAIL_INFO_45  INTEGER,
  SUP_MAIL_INFO_46  INTEGER,
  SUP_MAIL_INFO_47  INTEGER,
  SUP_MAIL_INFO_48  INTEGER,
  SUP_MAIL_INFO_49  INTEGER,
  SUP_MAIL_INFO_50  INTEGER,
  SUP_MAIL_INFO_51  INTEGER,
  SUP_MAIL_INFO_52  INTEGER,
  SUP_MAIL_INFO_53  INTEGER,
  SUP_MAIL_INFO_54  INTEGER,
  SUP_MAIL_INFO_55  INTEGER,
  SUP_MAIL_INFO_56  INTEGER,
  SUP_MAIL_INFO_57  INTEGER,
  SUP_MAIL_INFO_58  INTEGER,
  SUP_MAIL_INFO_59  INTEGER,
  SUP_MAIL_INFO_60  INTEGER,
  SUP_MAIL_INFO_61  INTEGER,
  SUP_MAIL_INFO_62  INTEGER,
  SUP_MAIL_INFO_63  INTEGER,
  SUP_MAIL_INFO_64  INTEGER,
  SUP_MAIL_INFO_65  INTEGER,
  SUP_MAIL_INFO_66  INTEGER,
  SUP_MAIL_INFO_67  INTEGER,
  SUP_MAIL_INFO_68  INTEGER,
  SUP_MAIL_INFO_69  INTEGER,
  SUP_MAIL_INFO_70  INTEGER,
  SUP_MAIL_INFO_71  INTEGER,
  SUP_MAIL_INFO_72  INTEGER,
  SUP_MAIL_INFO_73  INTEGER,
  SUP_MAIL_INFO_74  INTEGER,
  SUP_MAIL_INFO_75  INTEGER,
  SUP_MAIL_INFO_76  INTEGER,
  SUP_MAIL_INFO_77  INTEGER,
  SUP_MAIL_INFO_78  INTEGER,
  SUP_MAIL_INFO_79  INTEGER,
  SUP_MAIL_INFO_80  INTEGER,
  SUP_MAIL_INFO_81  INTEGER,
  SUP_MAIL_INFO_82  INTEGER,
  SUP_MAIL_INFO_83  INTEGER,
  SUP_MAIL_INFO_84  INTEGER,
  SUP_MAIL_INFO_85  INTEGER,
  SUP_MAIL_INFO_86  INTEGER,
  SUP_MAIL_INFO_87  INTEGER,
  SUP_MAIL_INFO_88  INTEGER,
  SUP_MAIL_INFO_89  INTEGER,
  SUP_MAIL_INFO_90  INTEGER,
  SUP_MAIL_INFO_91  INTEGER,
  SUP_MAIL_INFO_92  INTEGER,
  SUP_MAIL_INFO_93  INTEGER,
  SUP_MAIL_INFO_94  INTEGER,
  SUP_MAIL_INFO_95  INTEGER,
  SUP_MAIL_INFO_96  INTEGER,
  SUP_MAIL_INFO_97  INTEGER,
  SUP_MAIL_INFO_98  INTEGER,
  SUP_MAIL_INFO_99  INTEGER,
  SUP_MAIL_INFO_100 INTEGER,
  SUP_MAIL_INFO_101 INTEGER,
  SUP_MAIL_INFO_102 INTEGER,
  SUP_MAIL_INFO_103 INTEGER,
  SUP_MAIL_INFO_104 INTEGER,
  SUP_MAIL_INFO_105 INTEGER,
  SUP_MAIL_INFO_106 INTEGER,
  SUP_MAIL_INFO_107 INTEGER,
  SUP_MAIL_INFO_108 INTEGER,
  SUP_MAIL_INFO_109 INTEGER,
  SUP_MAIL_INFO_110 INTEGER,
  SUP_MAIL_INFO_111 INTEGER,
  SUP_MAIL_INFO_112 INTEGER,
  SUP_MAIL_INFO_113 INTEGER,
  SUP_MAIL_INFO_114 INTEGER,
  SUP_MAIL_INFO_115 INTEGER,
  SUP_MAIL_INFO_116 INTEGER,
  SUP_MAIL_INFO_117 INTEGER,
  SUP_MAIL_INFO_118 INTEGER,
  SUP_MAIL_INFO_119 INTEGER,
  SUP_MAIL_INFO_120 INTEGER,
  SUP_MAIL_INFO_121 INTEGER,
  SUP_MAIL_INFO_122 INTEGER,
  SUP_MAIL_INFO_123 INTEGER,
  SUP_MAIL_INFO_124 INTEGER,
  SUP_MAIL_INFO_125 INTEGER,
  SUP_MAIL_INFO_126 INTEGER,
  SUP_MAIL_INFO_127 INTEGER,
  SUP_MAIL_INFO_128 INTEGER,
  SUP_MAIL_INFO_129 INTEGER,
  SUP_MAIL_INFO_130 INTEGER,
  SUP_MAIL_INFO_131 INTEGER,
  SUP_MAIL_INFO_132 INTEGER,
  SUP_MAIL_INFO_133 INTEGER,
  SUP_MAIL_INFO_134 INTEGER,
  SUP_MAIL_INFO_135 INTEGER,
  SUP_MAIL_INFO_136 INTEGER,
  SUP_MAIL_INFO_137 INTEGER,
  SUP_MAIL_INFO_138 INTEGER,
  SUP_MAIL_INFO_139 INTEGER,
  SUP_MAIL_INFO_140 INTEGER,
  SUP_MAIL_INFO_141 INTEGER,
  SUP_MAIL_INFO_142 INTEGER,
  SUP_MAIL_INFO_143 INTEGER,
  SUP_MAIL_INFO_144 INTEGER,
  SUP_MAIL_INFO_145 INTEGER,
  SUP_MAIL_INFO_146 INTEGER,
  SUP_MAIL_INFO_147 INTEGER,
  SUP_MAIL_INFO_148 INTEGER,
  SUP_MAIL_INFO_149 INTEGER,
  SUP_MAIL_INFO_150 INTEGER,
  SUP_MAIL_INFO_151 INTEGER,
  SUP_MAIL_INFO_152 INTEGER,
  SUP_MAIL_INFO_153 INTEGER,
  SUP_MAIL_INFO_154 INTEGER,
  SUP_MAIL_INFO_155 INTEGER,
  SUP_MAIL_INFO_156 INTEGER,
  SUP_MAIL_INFO_157 INTEGER,
  SUP_MAIL_INFO_158 INTEGER,
  SUP_MAIL_INFO_159 INTEGER,
  SUP_MAIL_INFO_160 INTEGER,
  SUP_MAIL_INFO_161 INTEGER,
  SUP_MAIL_INFO_162 INTEGER,
  SUP_MAIL_INFO_163 INTEGER,
  SUP_MAIL_INFO_164 INTEGER,
  SUP_MAIL_INFO_165 INTEGER,
  SUP_MAIL_INFO_166 INTEGER,
  SUP_MAIL_INFO_167 INTEGER,
  SUP_MAIL_INFO_168 INTEGER,
  SUP_MAIL_INFO_169 INTEGER,
  SUP_MAIL_INFO_170 INTEGER,
  SUP_MAIL_INFO_171 INTEGER,
  SUP_MAIL_INFO_172 INTEGER,
  SUP_MAIL_INFO_173 INTEGER,
  SUP_MAIL_INFO_174 INTEGER,
  SUP_MAIL_INFO_175 INTEGER,
  SUP_MAIL_INFO_176 INTEGER,
  SUP_MAIL_INFO_177 INTEGER,
  SUP_MAIL_INFO_178 INTEGER,
  SUP_MAIL_INFO_179 INTEGER,
  SUP_MAIL_INFO_180 INTEGER,
  SUP_MAIL_INFO_181 INTEGER,
  SUP_MAIL_INFO_182 INTEGER,
  SUP_MAIL_INFO_183 INTEGER,
  SUP_MAIL_INFO_184 INTEGER,
  SUP_MAIL_INFO_185 INTEGER,
  SUP_MAIL_INFO_186 INTEGER,
  SUP_MAIL_INFO_187 INTEGER,
  SUP_MAIL_INFO_188 INTEGER,
  SUP_MAIL_INFO_189 INTEGER,
  SUP_MAIL_INFO_190 INTEGER,
  SUP_MAIL_INFO_191 INTEGER,
  SUP_MAIL_INFO_192 INTEGER,
  SUP_MAIL_INFO_193 INTEGER,
  SUP_MAIL_INFO_194 INTEGER,
  SUP_MAIL_INFO_195 INTEGER,
  SUP_MAIL_INFO_196 INTEGER,
  SUP_MAIL_INFO_197 INTEGER,
  SUP_MAIL_INFO_198 INTEGER,
  SUP_MAIL_INFO_199 INTEGER,
  SUP_MAIL_INFO_200 INTEGER,
  SUP_MAIL_INFO_201 INTEGER,
  SUP_MAIL_INFO_202 INTEGER,
  SUP_MAIL_INFO_203 INTEGER,
  SUP_MAIL_INFO_204 INTEGER,
  SUP_MAIL_INFO_205 INTEGER,
  SUP_MAIL_INFO_206 INTEGER,
  SUP_MAIL_INFO_207 INTEGER,
  SUP_MAIL_INFO_208 INTEGER,
  SUP_MAIL_INFO_209 INTEGER,
  SUP_MAIL_INFO_210 INTEGER,
  SUP_MAIL_INFO_211 INTEGER,
  SUP_MAIL_INFO_212 INTEGER,
  SUP_MAIL_INFO_213 INTEGER,
  SUP_MAIL_INFO_214 INTEGER,
  SUP_MAIL_INFO_215 INTEGER,
  SUP_MAIL_INFO_216 INTEGER,
  SUP_MAIL_INFO_217 INTEGER,
  SUP_MAIL_INFO_218 INTEGER,
  SUP_MAIL_INFO_219 INTEGER,
  SUP_MAIL_INFO_220 INTEGER,
  SUP_MAIL_INFO_221 INTEGER,
  SUP_MAIL_INFO_222 INTEGER,
  SUP_MAIL_INFO_223 INTEGER,
  SUP_MAIL_INFO_224 INTEGER,
  SUP_MAIL_INFO_225 INTEGER,
  SUP_MAIL_INFO_226 INTEGER,
  SUP_MAIL_INFO_227 INTEGER,
  SUP_MAIL_INFO_228 INTEGER,
  SUP_MAIL_INFO_229 INTEGER,
  SUP_MAIL_INFO_230 INTEGER,
  SUP_MAIL_INFO_231 INTEGER,
  SUP_MAIL_INFO_232 INTEGER,
  SUP_MAIL_INFO_233 INTEGER,
  SUP_MAIL_INFO_234 INTEGER,
  SUP_MAIL_INFO_235 INTEGER,
  SUP_MAIL_INFO_236 INTEGER,
  SUP_MAIL_INFO_237 INTEGER,
  SUP_MAIL_INFO_238 INTEGER,
  SUP_MAIL_INFO_239 INTEGER,
  SUP_MAIL_INFO_240 INTEGER,
  SUP_MAIL_INFO_241 INTEGER,
  SUP_MAIL_INFO_242 INTEGER,
  SUP_MAIL_INFO_243 INTEGER,
  SUP_MAIL_INFO_244 INTEGER,
  SUP_MAIL_INFO_245 INTEGER,
  SUP_MAIL_INFO_246 INTEGER,
  SUP_MAIL_INFO_247 INTEGER,
  SUP_MAIL_INFO_248 INTEGER,
  SUP_MAIL_INFO_249 INTEGER,
  SUP_MAIL_INFO_250 INTEGER,
  SUP_MAIL_INFO_251 INTEGER,
  SUP_MAIL_INFO_252 INTEGER,
  SUP_MAIL_INFO_253 INTEGER,
  SUP_MAIL_INFO_254 INTEGER,
  SUP_MAIL_INFO_255 INTEGER,
  SUP_MAIL_INFO_256 INTEGER,
  SUP_MAIL_INFO_257 INTEGER,
  SUP_MAIL_INFO_258 INTEGER,
  SUP_MAIL_INFO_259 INTEGER,
  SUP_MAIL_INFO_260 INTEGER,
  SUP_MAIL_INFO_261 INTEGER,
  SUP_MAIL_INFO_262 INTEGER,
  SUP_MAIL_INFO_263 INTEGER,
  SUP_MAIL_INFO_264 INTEGER,
  SUP_MAIL_INFO_265 INTEGER,
  SUP_MAIL_INFO_266 INTEGER,
  SUP_MAIL_INFO_267 INTEGER,
  SUP_MAIL_INFO_268 INTEGER,
  SUP_MAIL_INFO_269 INTEGER,
  SUP_MAIL_INFO_270 INTEGER,
  SUP_MAIL_INFO_271 INTEGER,
  SUP_MAIL_INFO_272 INTEGER,
  SUP_MAIL_INFO_273 INTEGER,
  SUP_MAIL_INFO_274 INTEGER,
  SUP_MAIL_INFO_275 INTEGER,
  SUP_MAIL_INFO_276 INTEGER,
  SUP_MAIL_INFO_277 INTEGER,
  SUP_MAIL_INFO_278 INTEGER,
  SUP_MAIL_INFO_279 INTEGER,
  SUP_MAIL_INFO_280 INTEGER,
  SUP_MAIL_INFO_281 INTEGER,
  SUP_MAIL_INFO_282 INTEGER,
  SUP_MAIL_INFO_283 INTEGER,
  SUP_MAIL_INFO_284 INTEGER,
  SUP_MAIL_INFO_285 INTEGER,
  SUP_MAIL_INFO_286 INTEGER,
  SUP_MAIL_INFO_287 INTEGER,
  SUP_MAIL_INFO_288 INTEGER,
  SUP_MAIL_INFO_289 INTEGER,
  SUP_MAIL_INFO_290 INTEGER,
  SUP_MAIL_INFO_291 INTEGER,
  SUP_MAIL_INFO_292 INTEGER,
  SUP_MAIL_INFO_293 INTEGER,
  SUP_MAIL_INFO_294 INTEGER,
  SUP_MAIL_INFO_295 INTEGER,
  SUP_MAIL_INFO_296 INTEGER,
  SUP_MAIL_INFO_297 INTEGER,
  SUP_MAIL_INFO_298 INTEGER,
  SUP_MAIL_INFO_299 INTEGER,
  SUP_MAIL_INFO_300 INTEGER,
  SUP_MAIL_INFO_301 INTEGER,
  SUP_MAIL_INFO_302 INTEGER,
  SUP_MAIL_INFO_303 INTEGER,
  SUP_MAIL_INFO_304 INTEGER,
  SUP_MAIL_INFO_305 INTEGER,
  SUP_MAIL_INFO_306 INTEGER,
  SUP_MAIL_INFO_307 INTEGER,
  SUP_MAIL_INFO_308 INTEGER,
  SUP_MAIL_INFO_309 INTEGER,
  SUP_MAIL_INFO_310 INTEGER,
  SUP_MAIL_INFO_311 INTEGER,
  SUP_MAIL_INFO_312 INTEGER,
  SUP_MAIL_INFO_313 INTEGER,
  SUP_MAIL_INFO_314 INTEGER,
  SUP_MAIL_INFO_315 INTEGER,
  SUP_MAIL_INFO_316 INTEGER,
  SUP_MAIL_INFO_317 INTEGER,
  SUP_MAIL_INFO_318 INTEGER,
  SUP_MAIL_INFO_319 INTEGER,
  SUP_MAIL_INFO_320 INTEGER,
  SUP_MAIL_INFO_321 INTEGER,
  SUP_MAIL_INFO_322 INTEGER,
  SUP_MAIL_INFO_323 INTEGER,
  SUP_MAIL_INFO_324 INTEGER,
  SUP_MAIL_INFO_325 INTEGER,
  SUP_MAIL_INFO_326 INTEGER,
  SUP_MAIL_INFO_327 INTEGER,
  SUP_MAIL_INFO_328 INTEGER,
  SUP_MAIL_INFO_329 INTEGER,
  SUP_MAIL_INFO_330 INTEGER,
  SUP_MAIL_INFO_331 INTEGER,
  SUP_MAIL_INFO_332 INTEGER,
  SUP_MAIL_INFO_333 INTEGER,
  SUP_MAIL_INFO_334 INTEGER,
  SUP_MAIL_INFO_335 INTEGER,
  SUP_MAIL_INFO_336 INTEGER,
  SUP_MAIL_INFO_337 INTEGER,
  SUP_MAIL_INFO_338 INTEGER,
  SUP_MAIL_INFO_339 INTEGER,
  SUP_MAIL_INFO_340 INTEGER,
  SUP_MAIL_INFO_341 INTEGER,
  SUP_MAIL_INFO_342 INTEGER,
  SUP_MAIL_INFO_343 INTEGER,
  SUP_MAIL_INFO_344 INTEGER,
  SUP_MAIL_INFO_345 INTEGER,
  SUP_MAIL_INFO_346 INTEGER,
  SUP_MAIL_INFO_347 INTEGER,
  SUP_MAIL_INFO_348 INTEGER,
  SUP_MAIL_INFO_349 INTEGER,
  SUP_MAIL_INFO_350 INTEGER,
  SUP_MAIL_INFO_351 INTEGER,
  SUP_MAIL_INFO_352 INTEGER,
  SUP_MAIL_INFO_353 INTEGER,
  SUP_MAIL_INFO_354 INTEGER,
  SUP_MAIL_INFO_355 INTEGER,
  SUP_MAIL_INFO_356 INTEGER,
  SUP_MAIL_INFO_357 INTEGER,
  SUP_MAIL_INFO_358 INTEGER,
  SUP_MAIL_INFO_359 INTEGER,
  SUP_MAIL_INFO_360 INTEGER,
  SUP_MAIL_INFO_361 INTEGER,
  SUP_MAIL_INFO_362 INTEGER,
  SUP_MAIL_INFO_363 INTEGER,
  SUP_MAIL_INFO_364 INTEGER,
  SUP_MAIL_INFO_365 INTEGER,
  SUP_MAIL_INFO_366 INTEGER,
  SUP_MAIL_INFO_367 INTEGER,
  SUP_MAIL_INFO_368 INTEGER,
  SUP_MAIL_INFO_369 INTEGER,
  SUP_MAIL_INFO_370 INTEGER,
  SUP_MAIL_INFO_371 INTEGER,
  SUP_MAIL_INFO_372 INTEGER,
  SUP_MAIL_INFO_373 INTEGER,
  SUP_MAIL_INFO_374 INTEGER,
  SUP_MAIL_INFO_375 INTEGER,
  SUP_MAIL_INFO_376 INTEGER,
  SUP_MAIL_INFO_377 INTEGER,
  SUP_MAIL_INFO_378 INTEGER,
  SUP_MAIL_INFO_379 INTEGER,
  SUP_MAIL_INFO_380 INTEGER,
  SUP_MAIL_INFO_381 INTEGER,
  SUP_MAIL_INFO_382 INTEGER,
  SUP_MAIL_INFO_383 INTEGER,
  SUP_MAIL_INFO_384 INTEGER,
  SUP_MAIL_INFO_385 INTEGER,
  SUP_MAIL_INFO_386 INTEGER,
  SUP_MAIL_INFO_387 INTEGER,
  SUP_MAIL_INFO_388 INTEGER,
  SUP_MAIL_INFO_389 INTEGER,
  SUP_MAIL_INFO_390 INTEGER,
  SUP_MAIL_INFO_391 INTEGER,
  SUP_MAIL_INFO_392 INTEGER,
  SUP_MAIL_INFO_393 INTEGER,
  SUP_MAIL_INFO_394 INTEGER,
  SUP_MAIL_INFO_395 INTEGER,
  SUP_MAIL_INFO_396 INTEGER,
  SUP_MAIL_INFO_397 INTEGER,
  SUP_MAIL_INFO_398 INTEGER,
  SUP_MAIL_INFO_399 INTEGER,
  SUP_MAIL_INFO_400 INTEGER,
  SUP_MAIL_INFO_401 INTEGER,
  SUP_MAIL_INFO_402 INTEGER,
  SUP_MAIL_INFO_403 INTEGER,
  SUP_MAIL_INFO_404 INTEGER,
  SUP_MAIL_INFO_405 INTEGER,
  SUP_MAIL_INFO_406 INTEGER,
  SUP_MAIL_INFO_407 INTEGER,
  SUP_MAIL_INFO_408 INTEGER,
  SUP_MAIL_INFO_409 INTEGER,
  SUP_MAIL_INFO_410 INTEGER,
  SUP_MAIL_INFO_411 INTEGER,
  SUP_MAIL_INFO_412 INTEGER,
  SUP_MAIL_INFO_413 INTEGER,
  SUP_MAIL_INFO_414 INTEGER,
  SUP_MAIL_INFO_415 INTEGER,
  SUP_MAIL_INFO_416 INTEGER,
  SUP_MAIL_INFO_417 INTEGER,
  SUP_MAIL_INFO_418 INTEGER,
  SUP_MAIL_INFO_419 INTEGER,
  SUP_MAIL_INFO_420 INTEGER,
  SUP_MAIL_INFO_421 INTEGER,
  SUP_MAIL_INFO_422 INTEGER,
  SUP_MAIL_INFO_423 INTEGER,
  SUP_MAIL_INFO_424 INTEGER,
  SUP_MAIL_INFO_425 INTEGER,
  SUP_MAIL_INFO_426 INTEGER,
  SUP_MAIL_INFO_427 INTEGER,
  SUP_MAIL_INFO_428 INTEGER,
  SUP_MAIL_INFO_429 INTEGER,
  SUP_MAIL_INFO_430 INTEGER,
  SUP_MAIL_INFO_431 INTEGER,
  SUP_MAIL_INFO_432 INTEGER,
  SUP_MAIL_INFO_433 INTEGER,
  SUP_MAIL_INFO_434 INTEGER,
  SUP_MAIL_INFO_435 INTEGER,
  SUP_MAIL_INFO_436 INTEGER,
  SUP_MAIL_INFO_437 INTEGER,
  SUP_MAIL_INFO_438 INTEGER,
  SUP_MAIL_INFO_439 INTEGER,
  SUP_MAIL_INFO_440 INTEGER,
  SUP_MAIL_INFO_441 INTEGER,
  SUP_MAIL_INFO_442 INTEGER,
  SUP_MAIL_INFO_443 INTEGER,
  SUP_MAIL_INFO_444 INTEGER,
  SUP_MAIL_INFO_445 INTEGER,
  SUP_MAIL_INFO_446 INTEGER,
  SUP_MAIL_INFO_447 INTEGER,
  SUP_MAIL_INFO_448 INTEGER,
  SUP_MAIL_INFO_449 INTEGER,
  SUP_MAIL_INFO_450 INTEGER,
  SUP_MAIL_INFO_451 INTEGER,
  SUP_MAIL_INFO_452 INTEGER,
  SUP_MAIL_INFO_453 INTEGER,
  SUP_MAIL_INFO_454 INTEGER,
  SUP_MAIL_INFO_455 INTEGER,
  SUP_MAIL_INFO_456 INTEGER,
  SUP_MAIL_INFO_457 INTEGER,
  SUP_MAIL_INFO_458 INTEGER,
  SUP_MAIL_INFO_459 INTEGER,
  SUP_MAIL_INFO_460 INTEGER,
  SUP_MAIL_INFO_461 INTEGER,
  SUP_MAIL_INFO_462 INTEGER,
  SUP_MAIL_INFO_463 INTEGER,
  SUP_MAIL_INFO_464 INTEGER,
  SUP_MAIL_INFO_465 INTEGER,
  SUP_MAIL_INFO_466 INTEGER,
  SUP_MAIL_INFO_467 INTEGER,
  SUP_MAIL_INFO_468 INTEGER,
  SUP_MAIL_INFO_469 INTEGER,
  SUP_MAIL_INFO_470 INTEGER,
  SUP_MAIL_INFO_471 INTEGER,
  SUP_MAIL_INFO_472 INTEGER,
  SUP_MAIL_INFO_473 INTEGER,
  SUP_MAIL_INFO_474 INTEGER,
  SUP_MAIL_INFO_475 INTEGER,
  SUP_MAIL_INFO_476 INTEGER,
  SUP_MAIL_INFO_477 INTEGER,
  SUP_MAIL_INFO_478 INTEGER,
  SUP_MAIL_INFO_479 INTEGER,
  SUP_MAIL_INFO_480 INTEGER,
  SUP_MAIL_INFO_481 INTEGER,
  SUP_MAIL_INFO_482 INTEGER,
  SUP_MAIL_INFO_483 INTEGER,
  SUP_MAIL_INFO_484 INTEGER,
  SUP_MAIL_INFO_485 INTEGER,
  SUP_MAIL_INFO_486 INTEGER,
  SUP_MAIL_INFO_487 INTEGER,
  SUP_MAIL_INFO_488 INTEGER,
  SUP_MAIL_INFO_489 INTEGER,
  SUP_MAIL_INFO_490 INTEGER,
  SUP_MAIL_INFO_491 INTEGER,
  SUP_MAIL_INFO_492 INTEGER,
  SUP_MAIL_INFO_493 INTEGER,
  SUP_MAIL_INFO_494 INTEGER,
  SUP_MAIL_INFO_495 INTEGER,
  SUP_MAIL_INFO_496 INTEGER,
  SUP_MAIL_INFO_497 INTEGER,
  SUP_MAIL_INFO_498 INTEGER,
  SUP_MAIL_INFO_499 INTEGER,
  SUP_MAIL_INFO_500 INTEGER,
  SUP_MAIL_INFO_501 INTEGER,
  SUP_MAIL_INFO_502 INTEGER,
  SUP_MAIL_INFO_503 INTEGER,
  SUP_MAIL_INFO_504 INTEGER,
  SUP_MAIL_INFO_505 INTEGER,
  SUP_MAIL_INFO_506 INTEGER,
  SUP_MAIL_INFO_507 INTEGER,
  SUP_MAIL_INFO_508 INTEGER,
  SUP_MAIL_INFO_509 INTEGER,
  SUP_MAIL_INFO_510 INTEGER,
  SUP_MAIL_INFO_511 INTEGER,
  SUP_MAIL_INFO_512 INTEGER,
  SUP_MAIL_INFO_513 INTEGER,
  SUP_MAIL_INFO_514 INTEGER,
  SUP_MAIL_INFO_515 INTEGER,
  SUP_MAIL_INFO_516 INTEGER,
  SUP_MAIL_INFO_517 INTEGER,
  SUP_MAIL_INFO_518 INTEGER,
  SUP_MAIL_INFO_519 INTEGER,
  SUP_MAIL_INFO_520 INTEGER,
  SUP_MAIL_INFO_521 INTEGER,
  SUP_MAIL_INFO_522 INTEGER,
  SUP_MAIL_INFO_523 INTEGER,
  SUP_MAIL_INFO_524 INTEGER,
  SUP_MAIL_INFO_525 INTEGER,
  SUP_MAIL_INFO_526 INTEGER,
  SUP_MAIL_INFO_527 INTEGER,
  SUP_MAIL_INFO_528 INTEGER,
  SUP_MAIL_INFO_529 INTEGER,
  SUP_MAIL_INFO_530 INTEGER,
  SUP_MAIL_INFO_531 INTEGER,
  SUP_MAIL_INFO_532 INTEGER,
  SUP_MAIL_INFO_533 INTEGER,
  SUP_MAIL_INFO_534 INTEGER,
  SUP_MAIL_INFO_535 INTEGER,
  SUP_MAIL_INFO_536 INTEGER,
  SUP_MAIL_INFO_537 INTEGER,
  SUP_MAIL_INFO_538 INTEGER,
  SUP_MAIL_INFO_539 INTEGER,
  SUP_MAIL_INFO_540 INTEGER,
  SUP_MAIL_INFO_541 INTEGER,
  SUP_MAIL_INFO_542 INTEGER,
  SUP_MAIL_INFO_543 INTEGER,
  SUP_MAIL_INFO_544 INTEGER,
  SUP_MAIL_INFO_545 INTEGER,
  SUP_MAIL_INFO_546 INTEGER,
  SUP_MAIL_INFO_547 INTEGER,
  SUP_MAIL_INFO_548 INTEGER,
  SUP_MAIL_INFO_549 INTEGER,
  SUP_MAIL_INFO_550 INTEGER,
  SUP_MAIL_INFO_551 INTEGER,
  SUP_MAIL_INFO_552 INTEGER,
  SUP_MAIL_INFO_553 INTEGER,
  SUP_MAIL_INFO_554 INTEGER,
  SUP_MAIL_INFO_555 INTEGER,
  SUP_MAIL_INFO_556 INTEGER,
  SUP_MAIL_INFO_557 INTEGER,
  SUP_MAIL_INFO_558 INTEGER,
  SUP_MAIL_INFO_559 INTEGER,
  SUP_MAIL_INFO_560 INTEGER,
  SUP_MAIL_INFO_561 INTEGER,
  SUP_MAIL_INFO_562 INTEGER,
  SUP_MAIL_INFO_563 INTEGER,
  SUP_MAIL_INFO_564 INTEGER,
  SUP_MAIL_INFO_565 INTEGER,
  SUP_MAIL_INFO_566 INTEGER,
  SUP_MAIL_INFO_567 INTEGER,
  SUP_MAIL_INFO_568 INTEGER,
  SUP_MAIL_INFO_569 INTEGER,
  SUP_MAIL_INFO_570 INTEGER,
  SUP_MAIL_INFO_571 INTEGER,
  SUP_MAIL_INFO_572 INTEGER,
  SUP_MAIL_INFO_573 INTEGER,
  SUP_MAIL_INFO_574 INTEGER,
  SUP_MAIL_INFO_575 INTEGER,
  SUP_MAIL_INFO_576 INTEGER,
  SUP_MAIL_INFO_577 INTEGER,
  SUP_MAIL_INFO_578 INTEGER,
  SUP_MAIL_INFO_579 INTEGER,
  SUP_MAIL_INFO_580 INTEGER,
  SUP_MAIL_INFO_581 INTEGER,
  SUP_MAIL_INFO_582 INTEGER,
  SUP_MAIL_INFO_583 INTEGER,
  SUP_MAIL_INFO_584 INTEGER,
  SUP_MAIL_INFO_585 INTEGER,
  SUP_MAIL_INFO_586 INTEGER,
  SUP_MAIL_INFO_587 INTEGER,
  SUP_MAIL_INFO_588 INTEGER,
  SUP_MAIL_INFO_589 INTEGER,
  SUP_MAIL_INFO_590 INTEGER,
  SUP_MAIL_INFO_591 INTEGER,
  SUP_MAIL_INFO_592 INTEGER,
  SUP_MAIL_INFO_593 INTEGER,
  SUP_MAIL_INFO_594 INTEGER,
  SUP_MAIL_INFO_595 INTEGER,
  constraint PK_MAIL_INFO primary key (MAIL_INFO_EM_ADDR)
)
organization index 
PCTTHRESHOLD 20
overflow 
INCLUDING LPSZPROFILE;


prompt
prompt Creating table MENU_DATA
prompt ========================
prompt
create table MENU_DATA
(
  MENU_DATA_EM_ADDR     number(19) not null,
  MENU_DATA_TYPE        INTEGER,
  MENU_DATA_SIZE        INTEGER,
  PROFIL120_EM_ADDR     INTEGER,
  PROFIL120_EM_ADDR_ORD INTEGER,
  constraint PK_MENU_DATA primary key (MENU_DATA_EM_ADDR)
)
organization index ;

prompt
prompt Creating table MENU_ITEM
prompt ========================
prompt
create table MENU_ITEM
(
  MENU_ITEM_EM_ADDR           number(19) not null,
  MENU_ITEM_TYPE              INTEGER,
  MENU_ITEM_ID                INTEGER,
  MENU_DATA122_EM_ADDR        INTEGER,
  FORM123_EM_ADDR             INTEGER,
  OPTION_PARAM124_EM_ADDR     INTEGER,
  MENU_DATA125_EM_ADDR        INTEGER,
  MENU_DATA122_EM_ADDR_ORD    INTEGER,
  FORM123_EM_ADDR_ORD         INTEGER,
  OPTION_PARAM124_EM_ADDR_ORD INTEGER,
  MENU_DATA125_EM_ADDR_ORD    INTEGER,
  constraint PK_MENU_ITEM primary key (MENU_ITEM_EM_ADDR)
)
organization index ;

prompt
prompt Creating table MENU_XMLDATA
prompt ===========================
prompt
create table MENU_XMLDATA
(
  MENU_XMLDATA_EM_ADDR     number(19) not null,
  MENU_XMLDATA_ID          INTEGER,
  MENU_XMLDATA_SIZE        INTEGER,
  PARAM_MENU_XMLDATA       BLOB,
  MENU_DATA121_EM_ADDR     INTEGER,
  MENU_DATA121_EM_ADDR_ORD INTEGER,
  constraint PK_MENU_XMLDATA primary key (MENU_XMLDATA_EM_ADDR)
)
organization index ;

prompt
prompt Creating table MOD
prompt ==================
prompt
create table MOD
(
  MOD_EM_ADDR       number(19) not null,
  NUM_MOD           INTEGER,
  N0VERSION_MOD     INTEGER,
  MOD_DATA          BLOB,
  BDG30_EM_ADDR     INTEGER,
  BDG30_EM_ADDR_ORD INTEGER,
  constraint PK_MOD primary key (MOD_EM_ADDR)
)
organization index ;

prompt
prompt Creating table MODSCL
prompt =====================
prompt
create table MODSCL
(
  MODSCL_EM_ADDR    number(19) not null,
  NUM_MODSCL        INTEGER,
  SCL41_EM_ADDR     INTEGER,
  MOD42_EM_ADDR     INTEGER,
  SCL41_EM_ADDR_ORD INTEGER,
  MOD42_EM_ADDR_ORD INTEGER,
  constraint PK_MODSCL primary key (MODSCL_EM_ADDR)
)
organization index ;

prompt
prompt Creating table NCT
prompt ==================
prompt
create table NCT
(
  NCT_EM_ADDR        number(19) not null,
  NCT_FIELD          RAW(29),
  ID_CT              INTEGER,
  NUM_CT             INTEGER,
  NOM                NVARCHAR2(60),
  LABEL              NVARCHAR2(120),
  TYPE_CT            INTEGER,
  USER_CREATE_NCT    NVARCHAR2(60),
  DATE_CREATE_NCT    FLOAT,
  USER_MODIFY_NCT    NVARCHAR2(60),
  DATE_MODIFY_NCT    FLOAT,
  DATE_MODIFY_VALEUR FLOAT,
  constraint PK_NCT primary key (NCT_EM_ADDR)
)
organization index ;

prompt
prompt Creating table NMC
prompt ==================
prompt
create table NMC
(
  NMC_EM_ADDR       number(19) not null,
  NMC_FIELD         INTEGER,
  NIVEAU            INTEGER,
  NMC_LEAD_TIME     INTEGER,
  COEF_PERTE        FLOAT,
  NMC_ANNEE_DEBUT   INTEGER,
  NMC_PERIODE_DEBUT INTEGER,
  NMC_ANNEE_FIN     INTEGER,
  NMC_PERIODE_FIN   INTEGER,
  QUTE              FLOAT,
  NMC_UNITE         INTEGER,
  NMC_TYPE          INTEGER,
  PERE_PRO_NMC      RAW(16),
  FILS_PRO_NMC      RAW(16),
  PARAM_NMC_1       INTEGER,
  PARAM_NMC_2       INTEGER,
  PARAM_NMC_3       INTEGER,
  PARAM_NMC_4       INTEGER,
  PARAM_NMC_5       INTEGER,
  PARAM_NMC_6       INTEGER,
  PARAM_NMC_7       INTEGER,
  PARAM_NMC_8       INTEGER,
  PARAM_NMC_9       INTEGER,
  PARAM_NMC_10      INTEGER,
  PARAM_NMC_11      INTEGER,
  PARAM_NMC_12      INTEGER,
  PARAM_NMC_13      INTEGER,
  PARAM_NMC_14      INTEGER,
  PARAM_NMC_15      INTEGER,
  FAM1_EM_ADDR      INTEGER,
  FAM1_EM_ADDR_ORD  INTEGER,
  constraint PK_NMC primary key (NMC_EM_ADDR)
)
organization index ;

prompt
prompt Creating table OFDETAIL
prompt =======================
prompt
create table OFDETAIL
(
  OFDETAIL_EM_ADDR      number(19) not null,
  ID_OF                 NVARCHAR2(60),
  QTE_OF                FLOAT,
  DATE_BESOIN_ORDO      FLOAT,
  DATE_BESOIN_PLANNING  FLOAT,
  DEBUT_OF              FLOAT,
  FIN_OF                FLOAT,
  SETUP_AVANT_DEBUT     FLOAT,
  SETUP_APRES_FIN       FLOAT,
  STATUS_ORDO           INTEGER,
  STATUS_OF             INTEGER,
  QTE_OF_REALISE        FLOAT,
  DATE_REALISE          FLOAT,
  NOTE_OF               NVARCHAR2(256),
  NOTACHE               INTEGER,
  PENALTYTIME           FLOAT,
  DATEPLANNING          FLOAT,
  QUANTITEINITIALE      FLOAT,
  DATEDEBUTINITIALE     FLOAT,
  DATEFININITIALE       FLOAT,
  LASTSTATUSOFAPPLIED   INTEGER,
  SUP_OFDETAIL          RAW(112),
  OFTYPE105_EM_ADDR     INTEGER,
  OFTYPE105_EM_ADDR_ORD INTEGER,
  constraint PK_OFDETAIL primary key (OFDETAIL_EM_ADDR)
)
organization index ;


prompt
prompt Creating table OFTASK
prompt =====================
prompt
create table OFTASK
(
  OFTASK_EM_ADDR             number(19) not null,
  ID_TASK                    NVARCHAR2(60),
  QTE_TASK                   FLOAT,
  STATUS_TASK                INTEGER,
  DEBUT_TASK                 FLOAT,
  FIN_TASK                   FLOAT,
  TYPE_TASK                  INTEGER,
  SUP_TASKDETAIL             RAW(96),
  OFDETAIL106_EM_ADDR        INTEGER,
  SETUPTYPE107_EM_ADDR       INTEGER,
  DETAILSERIE110_EM_ADDR     INTEGER,
  OFDETAIL106_EM_ADDR_ORD    INTEGER,
  SETUPTYPE107_EM_ADDR_ORD   INTEGER,
  DETAILSERIE110_EM_ADDR_ORD INTEGER,
  constraint PK_OFTASK primary key (OFTASK_EM_ADDR)
)
organization index ;

prompt
prompt Creating table OFTYPE
prompt =====================
prompt
create table OFTYPE
(
  OFTYPE_EM_ADDR     number(19) not null,
  N0_OF_TYPE         INTEGER,
  BDG104_EM_ADDR     INTEGER,
  BDG104_EM_ADDR_ORD INTEGER,
  constraint PK_OFTYPE primary key (OFTYPE_EM_ADDR)
)
organization index ;


prompt
prompt Creating table OPTION_PARAM
prompt ===========================
prompt
create table OPTION_PARAM
(
  OPTION_PARAM_EM_ADDR     number(19) not null,
  ID_OPTION                INTEGER,
  CLE_OPTION               NVARCHAR2(60),
  LIB_OPTION               NVARCHAR2(120),
  PARAM_OPTION             BLOB,
  USER_CREATE_OPTION_PARAM NVARCHAR2(60),
  DATE_CREATE_OPTION_PARAM FLOAT,
  USER_MODIFY_OPTION_PARAM NVARCHAR2(60),
  DATE_MODIFY_OPTION_PARAM FLOAT,
  OPTION_PARAM_DATA        BLOB,
  constraint PK_OPTION_PARAM primary key (OPTION_PARAM_EM_ADDR)
)
organization index ;


prompt
prompt Creating table OPTION_PARAM_LNK
prompt ===============================
prompt
create table OPTION_PARAM_LNK
(
  OPTION_PARAM_LNK_EM_ADDR    number(19) not null,
  N0_OPTION_PARAM_LNK         INTEGER,
  OPTION_PARAM152_EM_ADDR     INTEGER,
  OPTION_PARAM152_EM_ADDR_ORD INTEGER,
  constraint PK_OPTION_PARAM_LNK primary key (OPTION_PARAM_LNK_EM_ADDR)
)
organization index ;


prompt
prompt Creating table OPTION_PRV
prompt =========================
prompt
create table OPTION_PRV
(
  OPTION_PRV_EM_ADDR         number(19) not null,
  N0_OPTION_PRV              INTEGER,
  PRV95_EM_ADDR              INTEGER,
  OPTION_PARAM96_EM_ADDR     INTEGER,
  PRV95_EM_ADDR_ORD          INTEGER,
  OPTION_PARAM96_EM_ADDR_ORD INTEGER,
   constraint PK_OPTION_PRV primary key (OPTION_PRV_EM_ADDR)
)
organization index ;


prompt
prompt Creating table OPTION_SEL
prompt =========================
prompt
create table OPTION_SEL
(
  OPTION_SEL_EM_ADDR         number(19) not null,
  N0_OPTION_SEL              INTEGER,
  SEL92_EM_ADDR              INTEGER,
  OPTION_PARAM93_EM_ADDR     INTEGER,
  SEL92_EM_ADDR_ORD          INTEGER,
  OPTION_PARAM93_EM_ADDR_ORD INTEGER,
  constraint PK_OPTION_SEL primary key (OPTION_SEL_EM_ADDR)
)
organization index ;


prompt
prompt Creating table OPT_SETUPTYPE_LNK
prompt ================================
prompt
create table OPT_SETUPTYPE_LNK
(
  OPT_SETUPTYPE_LNK_EM_ADDR   number(19) not null,
  N0_OPTION_SETUPTYPE         INTEGER,
  OPTION_PARAM126_EM_ADDR     INTEGER,
  SETUPTYPE127_EM_ADDR        INTEGER,
  OPTION_PARAM126_EM_ADDR_ORD INTEGER,
  SETUPTYPE127_EM_ADDR_ORD    INTEGER,
  constraint PK_OPT_SETUPTYPE_LNK primary key (OPT_SETUPTYPE_LNK_EM_ADDR)
)
organization index ;

prompt
prompt Creating table PLAN_PVT
prompt =======================
prompt
create table PLAN_PVT
(
  PLAN_PVT_EM_ADDR number(19) not null,
  PRO_DIM          NVARCHAR2(60),
  TYPO             NVARCHAR2(60),
  CONCEPT          NVARCHAR2(60),
  TYPE_STOCK_MAG   NVARCHAR2(60),
  STOCK_MAG        FLOAT,
  AN_DEBUT         INTEGER,
  MOIS_DEBUT       INTEGER,
  JOUR_DEBUT       INTEGER,
  AN_FIN           INTEGER,
  MOIS_FIN         INTEGER,
  JOUR_FIN         INTEGER,
  PLAN_PVT_TEXT    NVARCHAR2(256),
  PARAM_PLAN_PVT   RAW(430),
  TYPO_ARTICLE     NVARCHAR2(60),
  constraint PK_PLAN_PVT primary key (PLAN_PVT_EM_ADDR)
)
organization index ;


prompt
prompt Creating table PRB
prompt ==================
prompt
create table PRB
(
  PRB_EM_ADDR       number(19) not null,
  ANNEE_PRV         INTEGER,
  M_PRV_1           FLOAT,
  M_PRV_2           FLOAT,
  M_PRV_3           FLOAT,
  M_PRV_4           FLOAT,
  M_PRV_5           FLOAT,
  M_PRV_6           FLOAT,
  M_PRV_7           FLOAT,
  M_PRV_8           FLOAT,
  M_PRV_9           FLOAT,
  M_PRV_10          FLOAT,
  M_PRV_11          FLOAT,
  M_PRV_12          FLOAT,
  M_PRV_13          FLOAT,
  M_PRV_14          FLOAT,
  RBP22_EM_ADDR     INTEGER,
  RBP22_EM_ADDR_ORD INTEGER,
  constraint PK_PRB primary key (PRB_EM_ADDR)
)
organization index ;


prompt
prompt Creating table PRM
prompt ==================
prompt
create table PRM
(
  PRM_EM_ADDR       number(19) not null,
  ANNEE_PRM         INTEGER,
  M_PRM_1           FLOAT,
  M_PRM_2           FLOAT,
  M_PRM_3           FLOAT,
  M_PRM_4           FLOAT,
  M_PRM_5           FLOAT,
  M_PRM_6           FLOAT,
  M_PRM_7           FLOAT,
  M_PRM_8           FLOAT,
  M_PRM_9           FLOAT,
  M_PRM_10          FLOAT,
  M_PRM_11          FLOAT,
  M_PRM_12          FLOAT,
  M_PRM_13          FLOAT,
  M_PRM_14          FLOAT,
  RPE29_EM_ADDR     INTEGER,
  RPE29_EM_ADDR_ORD INTEGER,
  constraint PK_PRM primary key (PRM_EM_ADDR)
)
organization index ;
 
prompt
prompt Creating table PROFIL
prompt =====================
prompt
create table PROFIL
(
  PROFIL_EM_ADDR       number(19) not null,
  PROFIL_CLE           NVARCHAR2(60),
  PROFIL_DESC          NVARCHAR2(120),
  USER_CREATE_PROFIL   NVARCHAR2(60),
  DATE_CREATE_PROFIL   FLOAT,
  USER_MODIFY_PROFIL   NVARCHAR2(60),
  DATE_MODIFY_PROFIL   FLOAT,
  PROFIL48_EM_ADDR     INTEGER,
  PROFIL48_EM_ADDR_ORD INTEGER,
  constraint PK_PROFIL primary key (PROFIL_EM_ADDR)
)
organization index ;


prompt
prompt Creating table PROFIL_DATA
prompt ==========================
prompt
create table PROFIL_DATA
(
  PROFIL_DATA_EM_ADDR         number(19) not null,
  PROFIL_DATA_TYPE            INTEGER,
  PROFIL_DATA_SIZE            INTEGER,
  PROFIL128_EM_ADDR           INTEGER,
  OPTION_PARAM138_EM_ADDR     INTEGER,
  PROFIL128_EM_ADDR_ORD       INTEGER,
  OPTION_PARAM138_EM_ADDR_ORD INTEGER,
  constraint PK_PROFIL_DATA primary key (PROFIL_DATA_EM_ADDR)
)
organization index ;

prompt
prompt Creating table PROFIL_LICENSE
prompt =============================
prompt
create table PROFIL_LICENSE
(
  PROFIL_LICENSE_EM_ADDR number(19) not null,
  N0_PROFIL_LICENSE      INTEGER,
  PROFIL144_EM_ADDR      INTEGER,
  LICENSE145_EM_ADDR     INTEGER,
  PROFIL144_EM_ADDR_ORD  INTEGER,
  LICENSE145_EM_ADDR_ORD INTEGER,
  constraint PK_PROFIL_LICENSE primary key (PROFIL_LICENSE_EM_ADDR)
)
organization index ;


prompt
prompt Creating table PROFIL_LNK
prompt =========================
prompt
create table PROFIL_LNK
(
  PROFIL_LNK_EM_ADDR          number(19) not null,
  N0_PROFIL_LNK               INTEGER,
  PROMO_PROFIL148_EM_ADDR     INTEGER,
  PROMO149_EM_ADDR            INTEGER,
  PROMO_PROFIL148_EM_ADDR_ORD INTEGER,
  PROMO149_EM_ADDR_ORD        INTEGER,
  constraint PK_PROFIL_LNK primary key (PROFIL_LNK_EM_ADDR)
)
organization index ;

prompt
prompt Creating table PROFIL_PRO_LNK
prompt =============================
prompt
create table PROFIL_PRO_LNK
(
  PROFIL_PRO_LNK_EM_ADDR      number(19) not null,
  N0_PROFIL_PRO_LNK           INTEGER,
  PROMO_PROFIL150_EM_ADDR     INTEGER,
  PROMO_PRO151_EM_ADDR        INTEGER,
  PROMO_PROFIL150_EM_ADDR_ORD INTEGER,
  PROMO_PRO151_EM_ADDR_ORD    INTEGER,
  constraint PK_PROFIL_PRO_LNK primary key (PROFIL_PRO_LNK_EM_ADDR)
)
organization index ;


prompt
prompt Creating table PROFIL_XMLDATA
prompt =============================
prompt
create table PROFIL_XMLDATA
(
  PROFIL_XMLDATA_EM_ADDR     number(19) not null,
  PROFIL_XMLDATA_ID          INTEGER,
  PROFIL_XMLDATA_SIZE        INTEGER,
  PARAM_PROFIL_XMLDATA       BLOB,
  PROFIL_DATA129_EM_ADDR     INTEGER,
  PROFIL_DATA129_EM_ADDR_ORD INTEGER,
  constraint PK_PROFIL_XMLDATA primary key (PROFIL_XMLDATA_EM_ADDR)
)
organization index ;

prompt
prompt Creating table PROMO
prompt ====================
prompt
create table PROMO
(
  PROMO_EM_ADDR              number(19) not null,
  JOUR_DEBUT_MAGASIN         INTEGER,
  MOIS_DEBUT_MAGASIN         INTEGER,
  AN_DEBUT_MAGASIN           INTEGER,
  JOUR_FIN_MAGASIN           INTEGER,
  MOIS_FIN_MAGASIN           INTEGER,
  AN_FIN_MAGASIN             INTEGER,
  MODE_DEBUT_LIVRAISON       INTEGER,
  JOUR_DEBUT_LIVRAISON       INTEGER,
  MOIS_DEBUT_LIVRAISON       INTEGER,
  AN_DEBUT_LIVRAISON         INTEGER,
  DECALAGE_DEBUT_LIVRAISON   INTEGER,
  MODE_FIN_LIVRAISON         INTEGER,
  JOUR_FIN_LIVRAISON         INTEGER,
  MOIS_FIN_LIVRAISON         INTEGER,
  AN_FIN_LIVRAISON           INTEGER,
  DECALAGE_FIN_LIVRAISON     INTEGER,
  JOUR_ALERTE                INTEGER,
  MOIS_ALERTE                INTEGER,
  AN_ALERTE                  INTEGER,
  MESSAGE_ALERTE_PROMO       NVARCHAR2(510),
  JOUR_VISITE                INTEGER,
  MOIS_VISIE                 INTEGER,
  AN_VISITE                  INTEGER,
  MESSAGE_VISITE_PROMO       NVARCHAR2(510),
  NOTE_PROMO                 NVARCHAR2(2000),
  USER_CREATE_PROMO          NVARCHAR2(60),
  DATE_CREATE_PROMO          FLOAT,
  BITFIELD_MODIFICATIONS     INTEGER,
  PROMO_DATA                 BLOB,
  PROMO_PROFIL55_EM_ADDR     INTEGER,
  OPTION_PARAM94_EM_ADDR     INTEGER,
  DIS99_EM_ADDR              INTEGER,
  PROMO_PROFIL55_EM_ADDR_ORD INTEGER,
  OPTION_PARAM94_EM_ADDR_ORD INTEGER,
  DIS99_EM_ADDR_ORD          INTEGER,
  constraint PK_PROMO primary key (PROMO_EM_ADDR)
)
organization index 
PCTTHRESHOLD 20
overflow 
INCLUDING PROMO_DATA;

prompt
prompt Creating table PROMO_GEO_LNK
prompt ============================
prompt
create table PROMO_GEO_LNK
(
  PROMO_GEO_LNK_EM_ADDR number(19) not null,
  GEO66_EM_ADDR         INTEGER,
  PROMO67_EM_ADDR       INTEGER,
  GEO66_EM_ADDR_ORD     INTEGER,
  PROMO67_EM_ADDR_ORD   INTEGER,
   constraint PK_PROMO_GEO_LNK primary key (PROMO_GEO_LNK_EM_ADDR)
)
organization index ;


prompt
prompt Creating table PROMO_PRO
prompt ========================
prompt
create table PROMO_PRO
(
  PROMO_PRO_EM_ADDR          number(19) not null,
  QTE_PROMO                  FLOAT,
  QTE_PROMO_VALIDE           FLOAT,
  QTE_HISTO                  FLOAT,
  QTE_CARNET                 FLOAT,
  UM_PROMO                   INTEGER,
  PRIX_PROMO                 FLOAT,
  QTE_BASELINE               FLOAT,
  QTE_UPLIFT                 FLOAT,
  QTE_UPLIFT_VALIDE          FLOAT,
  DISCOUNT                   FLOAT,
  PRIX_VENTE                 FLOAT,
  LOWEST_PRICE               FLOAT,
  TAUX_BASELINE_RESTANT      FLOAT,
  QTE_POST_PROMO             FLOAT,
  HORIZON_POST_PROMO         INTEGER,
  AVEC_REPORT_BASE           INTEGER,
  MODECARNET                 INTEGER,
  NOTE_PROMO_LISTE           NVARCHAR2(2000),
  PROMO_PRO_DATA             BLOB,
  PROMO_PROFIL56_EM_ADDR     INTEGER,
  FAM57_EM_ADDR              INTEGER,
  FAM58_EM_ADDR              INTEGER,
  CRTSERIE60_EM_ADDR         INTEGER,
  PROMO_PROFIL56_EM_ADDR_ORD INTEGER,
  FAM57_EM_ADDR_ORD          INTEGER,
  FAM58_EM_ADDR_ORD          INTEGER,
  CRTSERIE60_EM_ADDR_ORD     INTEGER,
  constraint PK_PROMO_PRO primary key (PROMO_PRO_EM_ADDR)
)
organization index 
PCTTHRESHOLD 20
overflow 
INCLUDING PROMO_PRO_DATA;


prompt
prompt Creating table PROMO_PROFIL
prompt ===========================
prompt
create table PROMO_PROFIL
(
  PROMO_PROFIL_EM_ADDR number(19) not null,
  NVERSION             INTEGER,
  constraint PK_PROMO_PROFIL primary key (PROMO_PROFIL_EM_ADDR)
)
organization index ;


prompt
prompt Creating table PROMO_PROFIL_QTY
prompt ===============================
prompt
create table PROMO_PROFIL_QTY
(
  PROMO_PROFIL_QTY_EM_ADDR    number(19) not null,
  NPAGEINDEX                  INTEGER,
  QTE_PERIODE_1               FLOAT,
  QTE_PERIODE_2               FLOAT,
  QTE_PERIODE_3               FLOAT,
  QTE_PERIODE_4               FLOAT,
  QTE_PERIODE_5               FLOAT,
  QTE_PERIODE_6               FLOAT,
  QTE_PERIODE_7               FLOAT,
  QTE_PERIODE_8               FLOAT,
  QTE_PERIODE_9               FLOAT,
  QTE_PERIODE_10              FLOAT,
  QTE_PERIODE_11              FLOAT,
  QTE_PERIODE_12              FLOAT,
  QTE_PERIODE_13              FLOAT,
  QTE_PERIODE_14              FLOAT,
  PROMO_PROFIL111_EM_ADDR     INTEGER,
  PROMO_PROFIL111_EM_ADDR_ORD INTEGER,
  constraint PK_PROMO_PROFIL_QTY primary key (PROMO_PROFIL_QTY_EM_ADDR)
)
organization index ;


prompt
prompt Creating table PROMO_PROMO_PRO_LNK
prompt ==================================
prompt
create table PROMO_PROMO_PRO_LNK
(
  PROMO_PROMO_PRO_LNK_EM_ADDR number(19) not null,
  PROMO68_EM_ADDR             INTEGER,
  PROMO_PRO69_EM_ADDR         INTEGER,
  PROMO68_EM_ADDR_ORD         INTEGER,
  PROMO_PRO69_EM_ADDR_ORD     INTEGER,
  constraint PK_PROMO_PROMO_PRO_LNK primary key (PROMO_PROMO_PRO_LNK_EM_ADDR)
)
organization index ;


prompt
prompt Creating table PROMO_PRO_CRTSERIE
prompt =================================
prompt
create table PROMO_PRO_CRTSERIE
(
  PROMO_PRO_CRTSERIE_EM_ADDR number(19) not null,
  N0_PROMO_PRO_CRTSERIE      INTEGER,
  PROMO_PRO142_EM_ADDR       INTEGER,
  CRTSERIE143_EM_ADDR        INTEGER,
  PROMO_PRO142_EM_ADDR_ORD   INTEGER,
  CRTSERIE143_EM_ADDR_ORD    INTEGER,
  constraint PK_PROMO_PRO_CRTSERIE primary key (PROMO_PRO_CRTSERIE_EM_ADDR)
)
organization index ;


prompt
prompt Creating table PROMO_PRO_VCT
prompt ============================
prompt
create table PROMO_PRO_VCT
(
  PROMO_PRO_VCT_EM_ADDR    number(19) not null,
  N0_PROMO_PRO_VCT         INTEGER,
  PROMO_PRO140_EM_ADDR     INTEGER,
  VCT141_EM_ADDR           INTEGER,
  PROMO_PRO140_EM_ADDR_ORD INTEGER,
  VCT141_EM_ADDR_ORD       INTEGER,
  constraint PK_PROMO_PRO_VCT primary key (PROMO_PRO_VCT_EM_ADDR)
)
organization index ;


prompt
prompt Creating table PRV
prompt ==================
prompt
create table PRV
(
  PRV_EM_ADDR     number(19) not null,
  PRV_SUP         RAW(18),
  PRV_CLE         NVARCHAR2(60),
  PRV_DESC        NVARCHAR2(120),
  UNITE_PRV       INTEGER,
  REGROUP_PRO     INTEGER,
  REGROUP_GEO     INTEGER,
  REGROUP_DIS     INTEGER,
  NB_PREVISION    INTEGER,
  JOUR_PREVISION  INTEGER,
  MOIS_PREVISION  INTEGER,
  ANNEE_PREVISION INTEGER,
  USER_CREATE_PRV NVARCHAR2(60),
  DATE_CREATE_PRV FLOAT,
  USER_MODIFY_PRV NVARCHAR2(60),
  DATE_MODIFY_PRV FLOAT,
  constraint PK_PRV primary key (PRV_EM_ADDR)
)
organization index ;


prompt
prompt Creating table PRVSEL
prompt =====================
prompt
create table PRVSEL
(
  PRVSEL_EM_ADDR    number(19) not null,
  PRV15_EM_ADDR     INTEGER,
  SEL16_EM_ADDR     INTEGER,
  PRV15_EM_ADDR_ORD INTEGER,
  SEL16_EM_ADDR_ORD INTEGER,
  constraint PK_PRVSEL primary key (PRVSEL_EM_ADDR)
)
organization index ;


prompt
prompt Creating table PVT
prompt ==================
prompt
create table PVT
(
  PVT_EM_ADDR      number(19) not null,
  PVT_CLE          NVARCHAR2(184),
  PVT_DESC         NVARCHAR2(120),
  ADR_PRO          RAW(16),
  ADR_GEO          RAW(16),
  ADR_DIS          RAW(16),
  USER_CREATE_PVT  NVARCHAR2(60),
  DATE_CREATE_PVT  FLOAT,
  USER_MODIFY_PVT  NVARCHAR2(60),
  DATE_MODIFY_PVT  FLOAT,
  PVT_PARENT_BDG   RAW(16),
  FAM4_EM_ADDR     INTEGER,
  GEO5_EM_ADDR     INTEGER,
  DIS6_EM_ADDR     INTEGER,
  FAM4_EM_ADDR_ORD INTEGER,
  GEO5_EM_ADDR_ORD INTEGER,
  DIS6_EM_ADDR_ORD INTEGER,
  constraint PK_pvt primary key (PVT_EM_ADDR)
)
organization index ;


prompt
prompt Creating table PVTCRT
prompt =====================
prompt
create table PVTCRT
(
  PVTCRT_EM_ADDR         number(19) not null,
  ID_CRT_PVT             INTEGER,
  NUMERO_CRT_PVT         INTEGER,
  PVT35_EM_ADDR          INTEGER,
  CRTSERIE36_EM_ADDR     INTEGER,
  PVT35_EM_ADDR_ORD      INTEGER,
  CRTSERIE36_EM_ADDR_ORD INTEGER,
  constraint PK_PVTCRT primary key (PVTCRT_EM_ADDR)
)
organization index ;


prompt
prompt Creating table RBP
prompt ==================
prompt
create table RBP
(
  RBP_EM_ADDR       number(19) not null,
  NUM_PRV           INTEGER,
  ANNEE_DEBUT_RBP   INTEGER,
  PERIODE_DEBUT_RBP INTEGER,
  ANNEE_FIN_RBP     INTEGER,
  PERIODE_FIN_RBP   INTEGER,
  MODE_RBP          INTEGER,
  DATE_MODIFY_RBP   FLOAT,
  SEL21_EM_ADDR     INTEGER,
  SEL21_EM_ADDR_ORD INTEGER,
  constraint PK_RBP primary key (RBP_EM_ADDR)
)
organization index ;


prompt
prompt Creating table RFC
prompt ==================
prompt
create table RFC
(
  RFC_EM_ADDR       number(19) not null,
  IDENT_CRT         INTEGER,
  NUMERO_CRT        INTEGER,
  FAM7_EM_ADDR      INTEGER,
  GEO8_EM_ADDR      INTEGER,
  DIS9_EM_ADDR      INTEGER,
  VCT10_EM_ADDR     INTEGER,
  FAM7_EM_ADDR_ORD  INTEGER,
  GEO8_EM_ADDR_ORD  INTEGER,
  DIS9_EM_ADDR_ORD  INTEGER,
  VCT10_EM_ADDR_ORD INTEGER,
  constraint PK_RFC primary key (RFC_EM_ADDR)
)
organization index ;


prompt
prompt Creating table RMS
prompt ==================
prompt
create table RMS
(
  RMS_EM_ADDR     number(19) not null,
  RMS_FIELD       RAW(18),
  RMS_CLE         NVARCHAR2(60),
  RMS_DESC        NVARCHAR2(120),
  USER_CREATE_RMS NVARCHAR2(60),
  DATE_CREATE_RMS FLOAT,
  USER_MODIFY_RMS NVARCHAR2(60),
  DATE_MODIFY_RMS FLOAT,
  constraint PK_RMS primary key (RMS_EM_ADDR)
)
organization index ;


prompt
prompt Creating table RPD
prompt ==================
prompt
create table RPD
(
  RPD_EM_ADDR       number(19) not null,
  NUM_SERIE         INTEGER,
  ANNEE_DEBUT       INTEGER,
  PERIODE_DEBUT     INTEGER,
  ANNEE_FIN         INTEGER,
  PERIODE_FIN       INTEGER,
  MODE_RPD          INTEGER,
  DATE_MODIFY_RPD   FLOAT,
  PVT17_EM_ADDR     INTEGER,
  PVT17_EM_ADDR_ORD INTEGER,
  constraint PK_RPD primary key (RPD_EM_ADDR)
)
organization index ;


prompt
prompt Creating table RPE
prompt ==================
prompt
create table RPE
(
  RPE_EM_ADDR       number(19) not null,
  PARAMETRE         INTEGER,
  ANNEE_DEBUT_RPE   INTEGER,
  PERIODE_DEBUT_RPE INTEGER,
  ANNEE_FIN_RPE     INTEGER,
  PERIODE_FIN_RPE   INTEGER,
  MODE_RPE          INTEGER,
  DATE_MODIFY_RPE   FLOAT,
  TRF25_EM_ADDR     INTEGER,
  DVS26_EM_ADDR     INTEGER,
  RMS27_EM_ADDR     INTEGER,
  SCL28_EM_ADDR     INTEGER,
  TRF25_EM_ADDR_ORD INTEGER,
  DVS26_EM_ADDR_ORD INTEGER,
  RMS27_EM_ADDR_ORD INTEGER,
  SCL28_EM_ADDR_ORD INTEGER,
  constraint PK_RPE primary key (RPE_EM_ADDR)
)
organization index ;


prompt
prompt Creating table RSP
prompt ==================
prompt
create table RSP
(
  RSP_EM_ADDR       number(19) not null,
  SEL13_EM_ADDR     INTEGER,
  PVT14_EM_ADDR     INTEGER,
  SEL13_EM_ADDR_ORD INTEGER,
  PVT14_EM_ADDR_ORD INTEGER,
  constraint PK_RSP primary key (RSP_EM_ADDR)
)
organization index ;


prompt
prompt Creating table SCL
prompt ==================
prompt
create table SCL
(
  SCL_EM_ADDR     number(19) not null,
  ID_SCL          INTEGER,
  SCL_FIELD       RAW(40),
  SCL_CLE         NVARCHAR2(60),
  SCL_DESC        NVARCHAR2(120),
  USER_CREATE_SCL NVARCHAR2(60),
  DATE_CREATE_SCL FLOAT,
  USER_MODIFY_SCL NVARCHAR2(60),
  DATE_MODIFY_SCL FLOAT,
  constraint PK_SCL primary key (SCL_EM_ADDR)
)
organization index ;


prompt
prompt Creating table SEL
prompt ==================
prompt
create table SEL
(
  SEL_EM_ADDR     number(19) not null,
  SEL_BUD         INTEGER,
  SEL_CLE         NVARCHAR2(184),
  SEL_DESC        NVARCHAR2(120),
  OPERANT_GEO     INTEGER,
  OPERANT_DIS     INTEGER,
  UNITE_SEL       INTEGER,
  EFFECTIF        INTEGER,
  JOUR_SELECT     INTEGER,
  MOIS_SELECT     INTEGER,
  ANNEE_SELECT    INTEGER,
  USER_CREATE_SEL NVARCHAR2(60),
  DATE_CREATE_SEL FLOAT,
  USER_MODIFY_SEL NVARCHAR2(60),
  DATE_MODIFY_SEL FLOAT,
  SEL_PARENT_BDG  RAW(16),
  constraint PK_SEL primary key (SEL_EM_ADDR)
)
organization index ;


prompt
prompt Creating table SELCRT
prompt =====================
prompt
create table SELCRT
(
  SELCRT_EM_ADDR         number(19) not null,
  ID_CRT_SEL             INTEGER,
  NUMERO_CRT_SEL         INTEGER,
  SEL53_EM_ADDR          INTEGER,
  CRTSERIE54_EM_ADDR     INTEGER,
  SEL53_EM_ADDR_ORD      INTEGER,
  CRTSERIE54_EM_ADDR_ORD INTEGER,
  constraint PK_SELCRT primary key (SELCRT_EM_ADDR)
)
organization index ;


prompt
prompt Creating table SELECT_SEL
prompt =========================
prompt
create table SELECT_SEL
(
  SELECT_SEL_EM_ADDR number(19) not null,
  ADR_PRV            RAW(16),
  PERE_SEL           RAW(16),
  FILS_SEL           RAW(16),
  BDG52_EM_ADDR      INTEGER,
  BDG52_EM_ADDR_ORD  INTEGER,
  constraint PK_SELECT_SEL primary key (SELECT_SEL_EM_ADDR)
)
organization index ;


prompt
prompt Creating table SERIE_BUDGET
prompt ===========================
prompt
create table SERIE_BUDGET
(
  SERIE_BUDGET_EM_ADDR    number(19) not null,
  N0_MODELE_BDG           INTEGER,
  N0_SERIE_BDG            INTEGER,
  ANNEE_DEBUT_SERIE_BDG   INTEGER,
  PERIODE_DEBUT_SERIE_BDG INTEGER,
  ANNEE_FIN_SERIE_BDG     INTEGER,
  PERIODE_FIN_SERIE_BDG   INTEGER,
  MODE_SERIE_BUDGET       INTEGER,
  DATE_MODIFY_SERIE_BDG   FLOAT,
  BDG70_EM_ADDR           INTEGER,
  EXO72_EM_ADDR           INTEGER,
  BDG70_EM_ADDR_ORD       INTEGER,
  EXO72_EM_ADDR_ORD       INTEGER,
  constraint PK_SERIE_BUDGET primary key (SERIE_BUDGET_EM_ADDR)
)
organization index ;


prompt
prompt Creating table SERIE_NMC
prompt ========================
prompt
create table SERIE_NMC
(
  SERIE_NMC_EM_ADDR       number(19) not null,
  N0_SERIE_NMC            INTEGER,
  ANNEE_DEBUT_SERIE_NMC   INTEGER,
  PERIODE_DEBUT_SERIE_NMC INTEGER,
  ANNEE_FIN_SERIE_NMC     INTEGER,
  PERIODE_FIN_SERIE_NMC   INTEGER,
  MODE_SERIE_NMC          INTEGER,
  DATE_MODIFY_SERIE_NMC   FLOAT,
  NMC116_EM_ADDR          INTEGER,
  NMC116_EM_ADDR_ORD      INTEGER,
  constraint PK_SERIE_NMC primary key (SERIE_NMC_EM_ADDR)
)
organization index ;


prompt
prompt Creating table SERIE_PVT
prompt ========================
prompt
create table SERIE_PVT
(
  SERIE_PVT_EM_ADDR       number(19) not null,
  N0_SERIE_PVT            INTEGER,
  ANNEE_DEBUT_SERIE_PVT   INTEGER,
  PERIODE_DEBUT_SERIE_PVT INTEGER,
  ANNEE_FIN_SERIE_PVT     INTEGER,
  PERIODE_FIN_SERIE_PVT   INTEGER,
  MODE_SERIE_PVT          INTEGER,
  DATE_MODIFY_SERIE_PVT   FLOAT,
  PVT19_EM_ADDR           INTEGER,
  PVT19_EM_ADDR_ORD       INTEGER,
  constraint PK_SERIE_PVT primary key (SERIE_PVT_EM_ADDR)
)
organization index ;

prompt
prompt Creating table SERIE_SEL
prompt ========================
prompt
create table SERIE_SEL
(
  SERIE_SEL_EM_ADDR       number(19) not null,
  N0_SERIE_SEL            INTEGER,
  ANNEE_DEBUT_SERIE_SEL   INTEGER,
  PERIODE_DEBUT_SERIE_SEL INTEGER,
  ANNEE_FIN_SERIE_SEL     INTEGER,
  PERIODE_FIN_SERIE_SEL   INTEGER,
  MODE_SERIE_SEL          INTEGER,
  DATE_MODIFY_SERIE_SEL   FLOAT,
  SEL23_EM_ADDR           INTEGER,
  SEL23_EM_ADDR_ORD       INTEGER,
  constraint PK_SERIE_SEL primary key (SERIE_SEL_EM_ADDR)
)
organization index ;


prompt
prompt Creating table SERIE_SUPPLIER
prompt =============================
prompt
create table SERIE_SUPPLIER
(
  SERIE_SUPPLIER_EM_ADDR number(19) not null,
  PRO_CLE                NVARCHAR2(60),
  GEO_CLE                NVARCHAR2(60),
  DIS_CLE                NVARCHAR2(60),
  SERIE_CLE              NVARCHAR2(60),
  SUPPLIER_CLE           NVARCHAR2(60),
  TYPO_CLE               NVARCHAR2(60),
  CONCEPT_CLE            NVARCHAR2(60),
  PARAM_SERIE_SUPPLIER   RAW(242),
  constraint PK_SERIE_SUPPLIER primary key (SERIE_SUPPLIER_EM_ADDR)
)
organization index ;


prompt
prompt Creating table SERIE_SUPPLIER2
prompt ==============================
prompt
create table SERIE_SUPPLIER2
(
  SERIE_SUPPLIER2_EM_ADDR       number(19) not null,
  N0_SERIE_SUPPLIER2            INTEGER,
  ANNEE_DEBUT_SERIE_SUPPLIER2   INTEGER,
  PERIODE_DEBUT_SERIE_SUPPLIER2 INTEGER,
  ANNEE_FIN_SERIE_SUPPLIER2     INTEGER,
  PERIODE_FIN_SERIE_SUPPLIER2   INTEGER,
  MODE_SERIE_SUPPLIER2          INTEGER,
  DATE_MODIFY_SERIE_SUPPLIER2   FLOAT,
  SUPPLIER118_EM_ADDR           INTEGER,
  SUPPLIER118_EM_ADDR_ORD       INTEGER,
constraint PK_SERIE_SUPPLIER2 primary key (SERIE_SUPPLIER2_EM_ADDR)
)
organization index ;


prompt
prompt Creating table SERINOTE
prompt =======================
prompt
create table SERINOTE
(
  SERINOTE_EM_ADDR number(19) not null,
  NOPAGE           INTEGER,
  DATE_MODIF_TEXTE INTEGER,
  TEXTE            NVARCHAR2(976),
  BDG3_EM_ADDR     INTEGER,
  BDG3_EM_ADDR_ORD INTEGER,
  constraint PK_SERINOTE primary key (SERINOTE_EM_ADDR)
)
organization index ;


prompt
prompt Creating table SETUPTYPE
prompt ========================
prompt
create table SETUPTYPE
(
  SETUPTYPE_EM_ADDR  number(19) not null,
  ID_SETUP           INTEGER,
  SETUP_CLE          NVARCHAR2(60),
  SETUP_DESC         NVARCHAR2(120),
  SETUP_COULEUR      INTEGER,
  SUP_SETUP          RAW(212),
  USER_CREATE_SETUP  NVARCHAR2(60),
  DATE_CREATE_SETUP  FLOAT,
  USER_MODIFY_SETUP  NVARCHAR2(60),
  DATE_MODIFY_SETUP  FLOAT,
  PRV132_EM_ADDR     INTEGER,
  PRV132_EM_ADDR_ORD INTEGER,
  constraint PK_SETUPTYPE primary key (SETUPTYPE_EM_ADDR)
)
organization index ;


prompt
prompt Creating table SUPPLIER
prompt =======================
prompt
create table SUPPLIER
(
  SUPPLIER_EM_ADDR  number(19) not null,
  ID_SUPPLIER       INTEGER,
  PERE_BDG          RAW(16),
  FILS_BDG          RAW(16),
  PARAM_SUP         RAW(470),
  BDG51_EM_ADDR     INTEGER,
  BDG51_EM_ADDR_ORD INTEGER,
  constraint PK_SUPPLIER primary key (SUPPLIER_EM_ADDR)
)
organization index ;


prompt
prompt Creating table SYSMESSAGE
prompt =========================
prompt
create table SYSMESSAGE
(
  SYSMESSAGE_EM_ADDR number(19) not null,
  CODE_LANGUE        NVARCHAR2(60),
  MESSAGE_ID         INTEGER,
  LIB_MESSAGE        NVARCHAR2(254),
  SYSMESSAGE_SUP     RAW(14),
  constraint PK_SYSMESSAGE primary key (SYSMESSAGE_EM_ADDR)
)
organization index ;


prompt
prompt Creating table TB_VERSION
prompt =========================
prompt
create table TB_VERSION
(
  ID          NUMBER not null,
  VERSION     NVARCHAR2(20),
  VERSIONDATE DATE default sysdate not null,
  REMARK      NVARCHAR2(200),
  STATE       NUMBER default 0 not null,
  constraint PK_RM_TB_VERSION primary key (ID)
)
organization index ;


prompt
prompt Creating table TIMENOTE
prompt =======================
prompt
create table TIMENOTE
(
  TIMENOTE_EM_ADDR       number(19) not null,
  ANNEE_DEB_NOTE         INTEGER,
  MOIS_DEB_NOTE          INTEGER,
  JOUR_DEB_NOTE          INTEGER,
  TIMETEXT               NVARCHAR2(522),
  DATE_MODIF_NOTE        FLOAT,
  ID_MODIF_NOTE          NVARCHAR2(60),
  TYPENOTE59_EM_ADDR     INTEGER,
  TYPENOTE59_EM_ADDR_ORD INTEGER,
  constraint PK_TIMENOTE primary key (TIMENOTE_EM_ADDR)
)
organization index ;


prompt
prompt Creating table TRF
prompt ==================
prompt
create table TRF
(
  TRF_EM_ADDR     number(19) not null,
  TRF_CLE         NVARCHAR2(60),
  TRF_DESC        NVARCHAR2(120),
  USER_CREATE_TRF NVARCHAR2(60),
  DATE_CREATE_TRF FLOAT,
  USER_MODIFY_TRF NVARCHAR2(60),
  DATE_MODIFY_TRF FLOAT,
  constraint PK_TRF primary key (TRF_EM_ADDR)
)
organization index ;


prompt
prompt Creating table TYPENOTE
prompt =======================
prompt
create table TYPENOTE
(
  TYPENOTE_EM_ADDR  number(19) not null,
  TYPE_NOTE         INTEGER,
  BDG47_EM_ADDR     INTEGER,
  BDG47_EM_ADDR_ORD INTEGER,
  constraint PK_TYPENOTE primary key (TYPENOTE_EM_ADDR)
)
organization index ;


prompt
prompt Creating table TYPE_SEQUENCE
prompt ============================
prompt
create table TYPE_SEQUENCE
(
  TYPE_SEQUENCE_EM_ADDR number(19) not null,
  TYPE_SEQUENCE_TYPE    INTEGER,
  BDG134_EM_ADDR        INTEGER,
  BDG134_EM_ADDR_ORD    INTEGER,
  constraint PK_TYPE_SEQUENCE primary key (TYPE_SEQUENCE_EM_ADDR)
)
organization index ;


prompt
prompt Creating table TYPE_STOCK
prompt =========================
prompt
create table TYPE_STOCK
(
  TYPE_STOCK_EM_ADDR number(19) not null,
  STOCK_MIN_CLE      NVARCHAR2(60),
  STOCK_MIN_DESC     NVARCHAR2(120),
  TYPE_STOCK_MIN     INTEGER,
  TYPE_STOCK_SUP     RAW(490),
  constraint PK_TYPE_STOCK primary key (TYPE_STOCK_EM_ADDR)
)
organization index ;


prompt
prompt Creating table USER_
prompt ====================
prompt
create table USER_
(
  USER__EM_ADDR        number(19) not null,
  ID_USER              INTEGER,
  USER_CLE             NVARCHAR2(60),
  USER_DESC            NVARCHAR2(120),
  USER_CREATE_USER     NVARCHAR2(60),
  DATE_CREATE_USER     FLOAT,
  USER_MODIFY_USER     NVARCHAR2(60),
  DATE_MODIFY_USER     FLOAT,
  PROFIL44_EM_ADDR     INTEGER,
  PROFIL44_EM_ADDR_ORD INTEGER,
  constraint PK_USER_ primary key (USER__EM_ADDR)
)
organization index ;



prompt
prompt Creating table USER_DATA
prompt ========================
prompt
create table USER_DATA
(
  USER_DATA_EM_ADDR    number(19) not null,
  USER_DATA_TYPE       INTEGER,
  USER_DATA_SIZE       INTEGER,
  USER_130_EM_ADDR     INTEGER,
  PVT139_EM_ADDR       INTEGER,
  USER_130_EM_ADDR_ORD INTEGER,
  PVT139_EM_ADDR_ORD   INTEGER,
  constraint PK_USER_DATA primary key (USER_DATA_EM_ADDR)
)
organization index ;


prompt
prompt Creating table USER_LICENSE
prompt ===========================
prompt
create table USER_LICENSE
(
  USER_LICENSE_EM_ADDR   number(19) not null,
  N0_USER_LICENSE        INTEGER,
  USER_146_EM_ADDR       INTEGER,
  LICENSE147_EM_ADDR     INTEGER,
  USER_146_EM_ADDR_ORD   INTEGER,
  LICENSE147_EM_ADDR_ORD INTEGER,
  constraint PK_USER_LICENSE primary key (USER_LICENSE_EM_ADDR)
)
organization index ;


prompt
prompt Creating table USER_SEL
prompt =======================
prompt
create table USER_SEL
(
  USER_SEL_EM_ADDR    number(19) not null,
  N0_USER_SEL         INTEGER,
  USER_97_EM_ADDR     INTEGER,
  SEL98_EM_ADDR       INTEGER,
  USER_97_EM_ADDR_ORD INTEGER,
  SEL98_EM_ADDR_ORD   INTEGER,
  constraint PK_USER_SEL primary key (USER_SEL_EM_ADDR)
)
organization index ;


prompt
prompt Creating table USER_XMLDATA
prompt ===========================
prompt
create table USER_XMLDATA
(
  USER_XMLDATA_EM_ADDR     number(19) not null,
  USER_XMLDATA_ID          INTEGER,
  USER_XMLDATA_SIZE        INTEGER,
  PARAM_USER_XMLDATA       BLOB,
  USER_DATA131_EM_ADDR     INTEGER,
  USER_DATA131_EM_ADDR_ORD INTEGER,
  constraint PK_USER_XMLDATA primary key (USER_XMLDATA_EM_ADDR)
)
organization index ;


prompt
prompt Creating table VCT
prompt ==================
prompt
create table VCT
(
  VCT_EM_ADDR     number(19) not null,
  VCT_FIELD       RAW(22),
  ID_CRT          INTEGER,
  NUM_CRT         INTEGER,
  VAL             NVARCHAR2(60),
  LIB_CRT         NVARCHAR2(120),
  LIB_CRT_COURT   NVARCHAR2(60),
  USER_CREATE_VCT NVARCHAR2(60),
  DATE_CREATE_VCT FLOAT,
  USER_MODIFY_VCT NVARCHAR2(60),
  DATE_MODIFY_VCT FLOAT,
  constraint PK_VCT primary key (VCT_EM_ADDR)
)
organization index ;

