create or replace view v_productunites as
select ID,
       C69,
       c70,
       c71,
       c72,
       c73,
       c74,
       c75,
       c76,
       c77,
       c78,
       um1,
       um2,
       um3,
       um4,
       um5,
       um6,
       um7,
       um8,
       um9,
       um10
  from (select f.fam_em_addr id,
               r.numero_crt,
               v.val,
               f.unite_1     um1,
               f.unite_2     um2,
               f.unite_3     um3,
               f.unite_4     um4,
               f.unite_5     um5,
               f.unite_6     um6,
               f.unite_7     um7,
               f.unite_8     um8,
               f.unite_9     um9,
               f.unite_10    um10
          from fam f
    left join rfc r
    on r.numero_crt between 69 and 78
     and f.fam_em_addr = r.fam7_em_addr
    left join  vct v on v.vct_em_addr = r.vct10_em_addr) pivot(max(val) for numero_crt in(69 as c69,
                                                                                     70 as c70,
                                                                                     71 as c71,
                                                                                     72 as c72,
                                                                                     73 as c73,
                                                                                     74 as c74,
                                                                                     75 as c75,
                                                                                     76 as c76,
                                                                                     77 as c77,
                                                                                     78 as c78));
