create unique index UIDX_BDG_BDG_CLE_KEY on BDG (ID_BDG, B_CLE);
create index idx_cdt_sel11_em_addr on cdt (sel11_em_addr);
create index idx_cdt_prv12_em_addr on cdt (prv12_em_addr);
create unique index UIDX_CRTSERIE_KEY on CRTSERIE (ID_CRT_SERIE, NUM_CRT_SERIE, VAL_CRT_SERIE);
create unique index UIDX_DIS_G_CLE_KEY on DIS (D_CLE);
create unique index UIDX_DVS_DVS_CLE_KEY on DVS (DVS_CLE);
create unique index UIDX_EXO_EXO_CLE_KEY on EXO (EXO_CLE);
create unique index UIDX_FAM_F_CLE_KEY on FAM (F_CLE);
create unique index UIDX_FORM_ETAT_CLE_KEY on FORM (ID_ETAT, CLE_ETAT);
create unique index UIDX_GEO_G_CLE_KEY on GEO (G_CLE);
create unique index UIDX_MAIL_INFO_KEY on MAIL_INFO (ID_TEMPLATE, CLE_TEMPLATE);
create unique index UIDX_NCT_NOM_CT_KEY on NCT (ID_CT, NUM_CT, NOM);
create unique index UIDX_OPTION_PARAM_KEY on OPTION_PARAM (ID_OPTION, CLE_OPTION);
create unique index UIDX_PROFIL_PROFIL_CLE_KEY on PROFIL (PROFIL_CLE);
create unique index UIDX_PRV_PRV_CLE_KEY on PRV (PRV_CLE);
create index idx_prvsel_prv_sel on prvsel (sel16_em_addr,prv15_em_addr);
create unique index UIDX_PVT_PVT_CLE_KEY on PVT (PVT_CLE);
create index idx_pvt_fam4_em_addr on pvt (fam4_em_addr);
create index idx_pvt_geo5_em_addr on pvt (geo5_em_addr);
create index idx_pvt_dis6_em_addr on pvt (dis6_em_addr);
create unique index UIDX_RMS_RMS_CLE_KEY on RMS (RMS_CLE);
create unique index UIDX_SCL_SCL_CLE_KEY on SCL (SCL_CLE);
create unique index UIDX_PVT_SEL_DBG_KEY on SEL (SEL_BUD, SEL_CLE);
create unique index UIDX_SEL_SEL_CLE_KEY on SEL (SEL_CLE);
create unique index UIDX_SERIE_SUPPLIER_KEY on SERIE_SUPPLIER (PRO_CLE, GEO_CLE, DIS_CLE);
create unique index UIDX_SETUPTYPE_PVT_CLE_KEY on SETUPTYPE (SETUP_CLE);
create unique index UIDX_SYSMESSAGE_KEY on SYSMESSAGE (CODE_LANGUE, MESSAGE_ID);
create unique index UIDX_TRF_TRF_CLE_KEY on TRF (TRF_CLE);
create unique index UIDX_USER_ID_USER_KEY on USER_ (ID_USER);
create unique index UIDX_USER_USER_CLE_KEY on USER_ (USER_CLE);
create unique index UIDX_VCT_VAL_CT_KEY on VCT (ID_CRT, NUM_CRT, VAL);
create index IDX_DON_w_Tpvt_ts_vs on DON_W (pvtID, TSID,Version);
create index IDX_prb_w_Tsel_ts_vs on prb_W (selID, TSID,Version);
create index IDX_bud_w_Tbdg_ts_vs on bud_W (bdgID, TSID,Version);
create index IDX_DON_M_pvt_ts_vs on DON_M (pvtID, TSID,Version);
create index IDX_PRB_M_sel_ts_vs on PRB_M (selID, TSID,Version);
create index IDX_BUD_M_bdg_ts_vs on BUD_M (bdgID, TSID,Version);

create index IDX_TRF_M_pvt_ts_vs on TRF_M (NodeID, TSID,Version);
create index IDX_TRF_W_pvt_ts_vs on TRF_W (NodeID, TSID,Version);
create index IDX_DVS_M_pvt_ts_vs on DVS_M (NodeID, TSID,Version);
create index IDX_DVS_W_pvt_ts_vs on DVS_W (NodeID, TSID,Version);
create index IDX_RMS_M_pvt_ts_vs on RMS_M (NodeID, TSID,Version);
create index IDX_RMS_W_pvt_ts_vs on RMS_W (NodeID, TSID,Version);
create index IDX_SCL_M_pvt_ts_vs on SCL_M (NodeID, TSID,Version);
create index IDX_SCL_W_pvt_ts_vs on SCL_W (NodeID, TSID,Version);
create index idx_don_d_ts_pvt on don_d(tsid,pvtid);
create index idx_prb_d_ts_pvt on prb_d(tsid,selid);
create index IDX_RFC_FAM on RFC (FAM7_EM_ADDR);