prompt
prompt Creating trigger TR_ADR_EMAIL
prompt =============================
prompt
CREATE OR REPLACE TRIGGER TR_ADR_EMAIL  BEFORE INSERT ON ADR_EMAIL FOR EACH ROW
 
BEGIN
SELECT SEQ_ADR_EMAIL.NEXTVAL INTO :NEW.ADR_EMAIL_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_BDG
prompt =======================
prompt
CREATE OR REPLACE TRIGGER TR_BDG  BEFORE INSERT ON BDG FOR EACH ROW
 
BEGIN
SELECT SEQ_BDG.NEXTVAL INTO :NEW.BDG_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_BDG_TASK
prompt ============================
prompt
CREATE OR REPLACE TRIGGER TR_BDG_TASK  BEFORE INSERT ON BDG_TASK FOR EACH ROW
 
BEGIN
SELECT SEQ_BDG_TASK.NEXTVAL INTO :NEW.BDG_TASK_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_BGC
prompt =======================
prompt
CREATE OR REPLACE TRIGGER TR_BGC  BEFORE INSERT ON BGC FOR EACH ROW
 
BEGIN
SELECT SEQ_BGC.NEXTVAL INTO :NEW.BGC_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_BUD
prompt =======================
prompt
CREATE OR REPLACE TRIGGER TR_BUD  BEFORE INSERT ON BUD FOR EACH ROW
 
BEGIN
SELECT SEQ_BUD.NEXTVAL INTO :NEW.BUD_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_CDT
prompt =======================
prompt
CREATE OR REPLACE TRIGGER TR_CDT  BEFORE INSERT ON CDT FOR EACH ROW
 
BEGIN
SELECT SEQ_CDT.NEXTVAL INTO :NEW.CDT_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_CONTENU_ETAT
prompt ================================
prompt
CREATE OR REPLACE TRIGGER TR_CONTENU_ETAT  BEFORE INSERT ON CONTENU_ETAT FOR EACH ROW
 
BEGIN
SELECT SEQ_CONTENU_ETAT.NEXTVAL INTO :NEW.CONTENU_ETAT_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_CRTSERIE
prompt ============================
prompt
CREATE OR REPLACE TRIGGER TR_CRTSERIE  BEFORE INSERT ON CRTSERIE FOR EACH ROW
 
BEGIN
SELECT SEQ_CRTSERIE.NEXTVAL INTO :NEW.CRTSERIE_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_DETAILREMARK
prompt ================================
prompt
CREATE OR REPLACE TRIGGER TR_DETAILREMARK  BEFORE INSERT ON DETAILREMARK FOR EACH ROW
 
BEGIN
SELECT SEQ_DETAILREMARK.NEXTVAL INTO :NEW.DETAILREMARK_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_DETAILSERIE
prompt ===============================
prompt
CREATE OR REPLACE TRIGGER TR_DETAILSERIE  BEFORE INSERT ON DETAILSERIE FOR EACH ROW
 
BEGIN
SELECT SEQ_DETAILSERIE.NEXTVAL INTO :NEW.DETAILSERIE_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_DETAILTYPE
prompt ==============================
prompt
CREATE OR REPLACE TRIGGER TR_DETAILTYPE  BEFORE INSERT ON DETAILTYPE FOR EACH ROW
 
BEGIN
SELECT SEQ_DETAILTYPE.NEXTVAL INTO :NEW.DETAILTYPE_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_DETAIL_SEQUENCE
prompt ===================================
prompt
CREATE OR REPLACE TRIGGER TR_DETAIL_SEQUENCE  BEFORE INSERT ON DETAIL_SEQUENCE FOR EACH ROW
 
BEGIN
SELECT SEQ_DETAIL_SEQUENCE.NEXTVAL INTO :NEW.DETAIL_SEQUENCE_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_DIS
prompt =======================
prompt
CREATE OR REPLACE TRIGGER TR_DIS  BEFORE INSERT ON DIS FOR EACH ROW
 
BEGIN
SELECT SEQ_DIS.NEXTVAL INTO :NEW.DIS_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_DON
prompt =======================
prompt
CREATE OR REPLACE TRIGGER TR_DON  BEFORE INSERT ON DON FOR EACH ROW
 
BEGIN
SELECT SEQ_DON.NEXTVAL INTO :NEW.DON_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_DON_BUDGET
prompt ==============================
prompt
CREATE OR REPLACE TRIGGER TR_DON_BUDGET  BEFORE INSERT ON DON_BUDGET FOR EACH ROW
 
BEGIN
SELECT SEQ_DON_BUDGET.NEXTVAL INTO :NEW.DON_BUDGET_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_DON_NMC
prompt ===========================
prompt
CREATE OR REPLACE TRIGGER TR_DON_NMC  BEFORE INSERT ON DON_NMC FOR EACH ROW
 
BEGIN
SELECT SEQ_DON_NMC.NEXTVAL INTO :NEW.DON_NMC_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_DON_PVT
prompt ===========================
prompt
CREATE OR REPLACE TRIGGER TR_DON_PVT  BEFORE INSERT ON DON_PVT FOR EACH ROW
 
BEGIN
SELECT SEQ_DON_PVT.NEXTVAL INTO :NEW.DON_PVT_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_DON_SEL
prompt ===========================
prompt
CREATE OR REPLACE TRIGGER TR_DON_SEL  BEFORE INSERT ON DON_SEL FOR EACH ROW
 
BEGIN
SELECT SEQ_DON_SEL.NEXTVAL INTO :NEW.DON_SEL_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_DON_SUPPLIER
prompt ================================
prompt
CREATE OR REPLACE TRIGGER TR_DON_SUPPLIER  BEFORE INSERT ON DON_SUPPLIER FOR EACH ROW
 
BEGIN
SELECT SEQ_DON_SUPPLIER.NEXTVAL INTO :NEW.DON_SUPPLIER_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_DVS
prompt =======================
prompt
CREATE OR REPLACE TRIGGER TR_DVS  BEFORE INSERT ON DVS FOR EACH ROW
 
BEGIN
SELECT SEQ_DVS.NEXTVAL INTO :NEW.DVS_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_EXO
prompt =======================
prompt
CREATE OR REPLACE TRIGGER TR_EXO  BEFORE INSERT ON EXO FOR EACH ROW
 
BEGIN
SELECT SEQ_EXO.NEXTVAL INTO :NEW.EXO_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_FAM
prompt =======================
prompt
CREATE OR REPLACE TRIGGER TR_FAM  BEFORE INSERT ON FAM FOR EACH ROW
 
BEGIN
SELECT SEQ_FAM.NEXTVAL INTO :NEW.FAM_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_FAMTRF
prompt ==========================
prompt
CREATE OR REPLACE TRIGGER TR_FAMTRF  BEFORE INSERT ON FAMTRF FOR EACH ROW
 
BEGIN
SELECT SEQ_FAMTRF.NEXTVAL INTO :NEW.FAMTRF_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_FORM
prompt ========================
prompt
CREATE OR REPLACE TRIGGER TR_FORM  BEFORE INSERT ON FORM FOR EACH ROW
 
BEGIN
SELECT SEQ_FORM.NEXTVAL INTO :NEW.FORM_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_FORM_CRTSERIE
prompt =================================
prompt
CREATE OR REPLACE TRIGGER TR_FORM_CRTSERIE  BEFORE INSERT ON FORM_CRTSERIE FOR EACH ROW
 
BEGIN
SELECT SEQ_FORM_CRTSERIE.NEXTVAL INTO :NEW.FORM_CRTSERIE_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_FORM_VCT
prompt ============================
prompt
CREATE OR REPLACE TRIGGER TR_FORM_VCT  BEFORE INSERT ON FORM_VCT FOR EACH ROW
 
BEGIN
SELECT SEQ_FORM_VCT.NEXTVAL INTO :NEW.FORM_VCT_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_GEO
prompt =======================
prompt
CREATE OR REPLACE TRIGGER TR_GEO  BEFORE INSERT ON GEO FOR EACH ROW
 
BEGIN
SELECT SEQ_GEO.NEXTVAL INTO :NEW.GEO_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_GEODVS
prompt ==========================
prompt
CREATE OR REPLACE TRIGGER TR_GEODVS  BEFORE INSERT ON GEODVS FOR EACH ROW
 
BEGIN
SELECT SEQ_GEODVS.NEXTVAL INTO :NEW.GEODVS_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_IST
prompt =======================
prompt
CREATE OR REPLACE TRIGGER TR_IST  BEFORE INSERT ON IST FOR EACH ROW
 
BEGIN
SELECT SEQ_IST.NEXTVAL INTO :NEW.IST_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_IST_CRTSERIE
prompt ================================
prompt
CREATE OR REPLACE TRIGGER TR_IST_CRTSERIE  BEFORE INSERT ON IST_CRTSERIE FOR EACH ROW
 
BEGIN
SELECT SEQ_IST_CRTSERIE.NEXTVAL INTO :NEW.IST_CRTSERIE_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_IST_DIS
prompt ===========================
prompt
CREATE OR REPLACE TRIGGER TR_IST_DIS  BEFORE INSERT ON IST_DIS FOR EACH ROW
 
BEGIN
SELECT SEQ_IST_DIS.NEXTVAL INTO :NEW.IST_DIS_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_IST_FAM
prompt ===========================
prompt
CREATE OR REPLACE TRIGGER TR_IST_FAM  BEFORE INSERT ON IST_FAM FOR EACH ROW
 
BEGIN
SELECT SEQ_IST_FAM.NEXTVAL INTO :NEW.IST_FAM_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_IST_GEO
prompt ===========================
prompt
CREATE OR REPLACE TRIGGER TR_IST_GEO  BEFORE INSERT ON IST_GEO FOR EACH ROW
 
BEGIN
SELECT SEQ_IST_GEO.NEXTVAL INTO :NEW.IST_GEO_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_IST_PARAM
prompt =============================
prompt
CREATE OR REPLACE TRIGGER TR_IST_PARAM  BEFORE INSERT ON IST_PARAM FOR EACH ROW
 
BEGIN
SELECT SEQ_IST_PARAM.NEXTVAL INTO :NEW.IST_PARAM_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_IST_PRV
prompt ===========================
prompt
CREATE OR REPLACE TRIGGER TR_IST_PRV  BEFORE INSERT ON IST_PRV FOR EACH ROW
 
BEGIN
SELECT SEQ_IST_PRV.NEXTVAL INTO :NEW.IST_PRV_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_IST_SCL
prompt ===========================
prompt
CREATE OR REPLACE TRIGGER TR_IST_SCL  BEFORE INSERT ON IST_SCL FOR EACH ROW
 
BEGIN
SELECT SEQ_IST_SCL.NEXTVAL INTO :NEW.IST_SCL_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_IST_SEL
prompt ===========================
prompt
CREATE OR REPLACE TRIGGER TR_IST_SEL  BEFORE INSERT ON IST_SEL FOR EACH ROW
 
BEGIN
SELECT SEQ_IST_SEL.NEXTVAL INTO :NEW.IST_SEL_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_IST_VCT
prompt ===========================
prompt
CREATE OR REPLACE TRIGGER TR_IST_VCT  BEFORE INSERT ON IST_VCT FOR EACH ROW
 
BEGIN
SELECT SEQ_IST_VCT.NEXTVAL INTO :NEW.IST_VCT_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_IST_XMLDATA
prompt ===============================
prompt
CREATE OR REPLACE TRIGGER TR_IST_XMLDATA  BEFORE INSERT ON IST_XMLDATA FOR EACH ROW
 
BEGIN
SELECT SEQ_IST_XMLDATA.NEXTVAL INTO :NEW.IST_XMLDATA_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_LANGUE
prompt ==========================
prompt
CREATE OR REPLACE TRIGGER TR_LANGUE  BEFORE INSERT ON LANGUE FOR EACH ROW
 
BEGIN
SELECT SEQ_LANGUE.NEXTVAL INTO :NEW.LANGUE_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_LIB_FAM_LANGUE
prompt ==================================
prompt
CREATE OR REPLACE TRIGGER TR_LIB_FAM_LANGUE  BEFORE INSERT ON LIB_FAM_LANGUE FOR EACH ROW
 
BEGIN
SELECT SEQ_LIB_FAM_LANGUE.NEXTVAL INTO :NEW.LIB_FAM_LANGUE_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_LICENSE
prompt ===========================
prompt
CREATE OR REPLACE TRIGGER TR_LICENSE  BEFORE INSERT ON LICENSE FOR EACH ROW
 
BEGIN
SELECT SEQ_LICENSE.NEXTVAL INTO :NEW.LICENSE_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_LIEN_ETAT_MAIL
prompt ==================================
prompt
CREATE OR REPLACE TRIGGER TR_LIEN_ETAT_MAIL  BEFORE INSERT ON LIEN_ETAT_MAIL FOR EACH ROW
 
BEGIN
SELECT SEQ_LIEN_ETAT_MAIL.NEXTVAL INTO :NEW.LIEN_ETAT_MAIL_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_LOGSESSION
prompt ==============================
prompt
CREATE OR REPLACE TRIGGER TR_LOGSESSION  BEFORE INSERT ON LOGSESSION FOR EACH ROW
 
BEGIN
SELECT SEQ_LOGSESSION.NEXTVAL INTO :NEW.LOGSESSION_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_MAIL_INFO
prompt =============================
prompt
CREATE OR REPLACE TRIGGER TR_MAIL_INFO  BEFORE INSERT ON MAIL_INFO FOR EACH ROW
 
BEGIN
SELECT SEQ_MAIL_INFO.NEXTVAL INTO :NEW.MAIL_INFO_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_MENU_DATA
prompt =============================
prompt
CREATE OR REPLACE TRIGGER TR_MENU_DATA  BEFORE INSERT ON MENU_DATA FOR EACH ROW
 
BEGIN
SELECT SEQ_MENU_DATA.NEXTVAL INTO :NEW.MENU_DATA_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_MENU_ITEM
prompt =============================
prompt
CREATE OR REPLACE TRIGGER TR_MENU_ITEM  BEFORE INSERT ON MENU_ITEM FOR EACH ROW
 
BEGIN
SELECT SEQ_MENU_ITEM.NEXTVAL INTO :NEW.MENU_ITEM_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_MENU_XMLDATA
prompt ================================
prompt
CREATE OR REPLACE TRIGGER TR_MENU_XMLDATA  BEFORE INSERT ON MENU_XMLDATA FOR EACH ROW
 
BEGIN
SELECT SEQ_MENU_XMLDATA.NEXTVAL INTO :NEW.MENU_XMLDATA_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_MOD
prompt =======================
prompt
CREATE OR REPLACE TRIGGER TR_MOD  BEFORE INSERT ON MOD FOR EACH ROW
 
BEGIN
SELECT SEQ_MOD.NEXTVAL INTO :NEW.MOD_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_MODSCL
prompt ==========================
prompt
CREATE OR REPLACE TRIGGER TR_MODSCL  BEFORE INSERT ON MODSCL FOR EACH ROW
 
BEGIN
SELECT SEQ_MODSCL.NEXTVAL INTO :NEW.MODSCL_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_NCT
prompt =======================
prompt
CREATE OR REPLACE TRIGGER TR_NCT  BEFORE INSERT ON NCT FOR EACH ROW
 
BEGIN
SELECT SEQ_NCT.NEXTVAL INTO :NEW.NCT_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_NMC
prompt =======================
prompt
CREATE OR REPLACE TRIGGER TR_NMC  BEFORE INSERT ON NMC FOR EACH ROW
 
BEGIN
SELECT SEQ_NMC.NEXTVAL INTO :NEW.NMC_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_OFDETAIL
prompt ============================
prompt
CREATE OR REPLACE TRIGGER TR_OFDETAIL  BEFORE INSERT ON OFDETAIL FOR EACH ROW
 
BEGIN
SELECT SEQ_OFDETAIL.NEXTVAL INTO :NEW.OFDETAIL_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_OFTASK
prompt ==========================
prompt
CREATE OR REPLACE TRIGGER TR_OFTASK  BEFORE INSERT ON OFTASK FOR EACH ROW
 
BEGIN
SELECT SEQ_OFTASK.NEXTVAL INTO :NEW.OFTASK_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_OFTYPE
prompt ==========================
prompt
CREATE OR REPLACE TRIGGER TR_OFTYPE  BEFORE INSERT ON OFTYPE FOR EACH ROW
 
BEGIN
SELECT SEQ_OFTYPE.NEXTVAL INTO :NEW.OFTYPE_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_OPTION_PARAM
prompt ================================
prompt
CREATE OR REPLACE TRIGGER TR_OPTION_PARAM  BEFORE INSERT ON OPTION_PARAM FOR EACH ROW
 
BEGIN
SELECT SEQ_OPTION_PARAM.NEXTVAL INTO :NEW.OPTION_PARAM_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_OPTION_PARAM_LNK
prompt ====================================
prompt
CREATE OR REPLACE TRIGGER TR_OPTION_PARAM_LNK  BEFORE INSERT ON OPTION_PARAM_LNK FOR EACH ROW
 
BEGIN
SELECT SEQ_OPTION_PARAM_LNK.NEXTVAL INTO :NEW.OPTION_PARAM_LNK_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_OPTION_PRV
prompt ==============================
prompt
CREATE OR REPLACE TRIGGER TR_OPTION_PRV  BEFORE INSERT ON OPTION_PRV FOR EACH ROW
 
BEGIN
SELECT SEQ_OPTION_PRV.NEXTVAL INTO :NEW.OPTION_PRV_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_OPTION_SEL
prompt ==============================
prompt
CREATE OR REPLACE TRIGGER TR_OPTION_SEL  BEFORE INSERT ON OPTION_SEL FOR EACH ROW
 
BEGIN
SELECT SEQ_OPTION_SEL.NEXTVAL INTO :NEW.OPTION_SEL_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_OPT_SETUPTYPE_LNK
prompt =====================================
prompt
CREATE OR REPLACE TRIGGER TR_OPT_SETUPTYPE_LNK  BEFORE INSERT ON OPT_SETUPTYPE_LNK FOR EACH ROW
 
BEGIN
SELECT SEQ_OPT_SETUPTYPE_LNK.NEXTVAL INTO :NEW.OPT_SETUPTYPE_LNK_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_PLAN_PVT
prompt ============================
prompt
CREATE OR REPLACE TRIGGER TR_PLAN_PVT  BEFORE INSERT ON PLAN_PVT FOR EACH ROW
 
BEGIN
SELECT SEQ_PLAN_PVT.NEXTVAL INTO :NEW.PLAN_PVT_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_PRB
prompt =======================
prompt
CREATE OR REPLACE TRIGGER TR_PRB  BEFORE INSERT ON PRB FOR EACH ROW
 
BEGIN
SELECT SEQ_PRB.NEXTVAL INTO :NEW.PRB_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_PRM
prompt =======================
prompt
CREATE OR REPLACE TRIGGER TR_PRM  BEFORE INSERT ON PRM FOR EACH ROW
 
BEGIN
SELECT SEQ_PRM.NEXTVAL INTO :NEW.PRM_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_PROFIL
prompt ==========================
prompt
CREATE OR REPLACE TRIGGER TR_PROFIL  BEFORE INSERT ON PROFIL FOR EACH ROW
 
BEGIN
SELECT SEQ_PROFIL.NEXTVAL INTO :NEW.PROFIL_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_PROFIL_DATA
prompt ===============================
prompt
CREATE OR REPLACE TRIGGER TR_PROFIL_DATA  BEFORE INSERT ON PROFIL_DATA FOR EACH ROW
 
BEGIN
SELECT SEQ_PROFIL_DATA.NEXTVAL INTO :NEW.PROFIL_DATA_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_PROFIL_LICENSE
prompt ==================================
prompt
CREATE OR REPLACE TRIGGER TR_PROFIL_LICENSE  BEFORE INSERT ON PROFIL_LICENSE FOR EACH ROW
 
BEGIN
SELECT SEQ_PROFIL_LICENSE.NEXTVAL INTO :NEW.PROFIL_LICENSE_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_PROFIL_LNK
prompt ==============================
prompt
CREATE OR REPLACE TRIGGER TR_PROFIL_LNK  BEFORE INSERT ON PROFIL_LNK FOR EACH ROW
 
BEGIN
SELECT SEQ_PROFIL_LNK.NEXTVAL INTO :NEW.PROFIL_LNK_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_PROFIL_PRO_LNK
prompt ==================================
prompt
CREATE OR REPLACE TRIGGER TR_PROFIL_PRO_LNK  BEFORE INSERT ON PROFIL_PRO_LNK FOR EACH ROW
 
BEGIN
SELECT SEQ_PROFIL_PRO_LNK.NEXTVAL INTO :NEW.PROFIL_PRO_LNK_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_PROFIL_XMLDATA
prompt ==================================
prompt
CREATE OR REPLACE TRIGGER TR_PROFIL_XMLDATA  BEFORE INSERT ON PROFIL_XMLDATA FOR EACH ROW
 
BEGIN
SELECT SEQ_PROFIL_XMLDATA.NEXTVAL INTO :NEW.PROFIL_XMLDATA_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_PROMO
prompt =========================
prompt
CREATE OR REPLACE TRIGGER TR_PROMO  BEFORE INSERT ON PROMO FOR EACH ROW
 
BEGIN
SELECT SEQ_PROMO.NEXTVAL INTO :NEW.PROMO_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_PROMO_GEO_LNK
prompt =================================
prompt
CREATE OR REPLACE TRIGGER TR_PROMO_GEO_LNK  BEFORE INSERT ON PROMO_GEO_LNK FOR EACH ROW
 
BEGIN
SELECT SEQ_PROMO_GEO_LNK.NEXTVAL INTO :NEW.PROMO_GEO_LNK_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_PROMO_PRO
prompt =============================
prompt
CREATE OR REPLACE TRIGGER TR_PROMO_PRO  BEFORE INSERT ON PROMO_PRO FOR EACH ROW
 
BEGIN
SELECT SEQ_PROMO_PRO.NEXTVAL INTO :NEW.PROMO_PRO_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_PROMO_PROFIL
prompt ================================
prompt
CREATE OR REPLACE TRIGGER TR_PROMO_PROFIL  BEFORE INSERT ON PROMO_PROFIL FOR EACH ROW
 
BEGIN
SELECT SEQ_PROMO_PROFIL.NEXTVAL INTO :NEW.PROMO_PROFIL_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_PROMO_PROFIL_QTY
prompt ====================================
prompt
CREATE OR REPLACE TRIGGER TR_PROMO_PROFIL_QTY  BEFORE INSERT ON PROMO_PROFIL_QTY FOR EACH ROW
 
BEGIN
SELECT SEQ_PROMO_PROFIL_QTY.NEXTVAL INTO :NEW.PROMO_PROFIL_QTY_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_PROMO_PROMO_PRO_LNK
prompt =======================================
prompt
CREATE OR REPLACE TRIGGER TR_PROMO_PROMO_PRO_LNK  BEFORE INSERT ON PROMO_PROMO_PRO_LNK FOR EACH ROW
 
BEGIN
SELECT SEQ_PROMO_PROMO_PRO_LNK.NEXTVAL INTO :NEW.PROMO_PROMO_PRO_LNK_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_PROMO_PRO_CRTSERIE
prompt ======================================
prompt
CREATE OR REPLACE TRIGGER TR_PROMO_PRO_CRTSERIE  BEFORE INSERT ON PROMO_PRO_CRTSERIE FOR EACH ROW
 
BEGIN
SELECT SEQ_PROMO_PRO_CRTSERIE.NEXTVAL INTO :NEW.PROMO_PRO_CRTSERIE_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_PROMO_PRO_VCT
prompt =================================
prompt
CREATE OR REPLACE TRIGGER TR_PROMO_PRO_VCT  BEFORE INSERT ON PROMO_PRO_VCT FOR EACH ROW
 
BEGIN
SELECT SEQ_PROMO_PRO_VCT.NEXTVAL INTO :NEW.PROMO_PRO_VCT_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_PRV
prompt =======================
prompt
CREATE OR REPLACE TRIGGER TR_PRV  BEFORE INSERT ON PRV FOR EACH ROW
 
BEGIN
SELECT SEQ_PRV.NEXTVAL INTO :NEW.PRV_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_PRVSEL
prompt ==========================
prompt
CREATE OR REPLACE TRIGGER TR_PRVSEL  BEFORE INSERT ON PRVSEL FOR EACH ROW
 
BEGIN
SELECT SEQ_PRVSEL.NEXTVAL INTO :NEW.PRVSEL_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_PVT
prompt =======================
prompt
CREATE OR REPLACE TRIGGER TR_PVT  BEFORE INSERT ON PVT FOR EACH ROW
 
BEGIN
SELECT SEQ_PVT.NEXTVAL INTO :NEW.PVT_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_PVTCRT
prompt ==========================
prompt
CREATE OR REPLACE TRIGGER TR_PVTCRT  BEFORE INSERT ON PVTCRT FOR EACH ROW
 
BEGIN
SELECT SEQ_PVTCRT.NEXTVAL INTO :NEW.PVTCRT_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_RBP
prompt =======================
prompt
CREATE OR REPLACE TRIGGER TR_RBP  BEFORE INSERT ON RBP FOR EACH ROW
 
BEGIN
SELECT SEQ_RBP.NEXTVAL INTO :NEW.RBP_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_RFC
prompt =======================
prompt
CREATE OR REPLACE TRIGGER TR_RFC  BEFORE INSERT ON RFC FOR EACH ROW
 
BEGIN
SELECT SEQ_RFC.NEXTVAL INTO :NEW.RFC_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_RMS
prompt =======================
prompt
CREATE OR REPLACE TRIGGER TR_RMS  BEFORE INSERT ON RMS FOR EACH ROW
 
BEGIN
SELECT SEQ_RMS.NEXTVAL INTO :NEW.RMS_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_RPD
prompt =======================
prompt
CREATE OR REPLACE TRIGGER TR_RPD  BEFORE INSERT ON RPD FOR EACH ROW
 
BEGIN
SELECT SEQ_RPD.NEXTVAL INTO :NEW.RPD_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_RPE
prompt =======================
prompt
CREATE OR REPLACE TRIGGER TR_RPE  BEFORE INSERT ON RPE FOR EACH ROW
 
BEGIN
SELECT SEQ_RPE.NEXTVAL INTO :NEW.RPE_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_RSP
prompt =======================
prompt
CREATE OR REPLACE TRIGGER TR_RSP  BEFORE INSERT ON RSP FOR EACH ROW
 
BEGIN
SELECT SEQ_RSP.NEXTVAL INTO :NEW.RSP_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_SCL
prompt =======================
prompt
CREATE OR REPLACE TRIGGER TR_SCL  BEFORE INSERT ON SCL FOR EACH ROW
 
BEGIN
SELECT SEQ_SCL.NEXTVAL INTO :NEW.SCL_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_SEL
prompt =======================
prompt
CREATE OR REPLACE TRIGGER TR_SEL  BEFORE INSERT ON SEL FOR EACH ROW
 
BEGIN
SELECT SEQ_SEL.NEXTVAL INTO :NEW.SEL_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_SELCRT
prompt ==========================
prompt
CREATE OR REPLACE TRIGGER TR_SELCRT  BEFORE INSERT ON SELCRT FOR EACH ROW
 
BEGIN
SELECT SEQ_SELCRT.NEXTVAL INTO :NEW.SELCRT_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_SELECT_SEL
prompt ==============================
prompt
CREATE OR REPLACE TRIGGER TR_SELECT_SEL  BEFORE INSERT ON SELECT_SEL FOR EACH ROW
 
BEGIN
SELECT SEQ_SELECT_SEL.NEXTVAL INTO :NEW.SELECT_SEL_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_SERIE_BUDGET
prompt ================================
prompt
CREATE OR REPLACE TRIGGER TR_SERIE_BUDGET  BEFORE INSERT ON SERIE_BUDGET FOR EACH ROW
 
BEGIN
SELECT SEQ_SERIE_BUDGET.NEXTVAL INTO :NEW.SERIE_BUDGET_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_SERIE_NMC
prompt =============================
prompt
CREATE OR REPLACE TRIGGER TR_SERIE_NMC  BEFORE INSERT ON SERIE_NMC FOR EACH ROW
 
BEGIN
SELECT SEQ_SERIE_NMC.NEXTVAL INTO :NEW.SERIE_NMC_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_SERIE_PVT
prompt =============================
prompt
CREATE OR REPLACE TRIGGER TR_SERIE_PVT  BEFORE INSERT ON SERIE_PVT FOR EACH ROW
 
BEGIN
SELECT SEQ_SERIE_PVT.NEXTVAL INTO :NEW.SERIE_PVT_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_SERIE_SEL
prompt =============================
prompt
CREATE OR REPLACE TRIGGER TR_SERIE_SEL  BEFORE INSERT ON SERIE_SEL FOR EACH ROW
 
BEGIN
SELECT SEQ_SERIE_SEL.NEXTVAL INTO :NEW.SERIE_SEL_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_SERIE_SUPPLIER
prompt ==================================
prompt
CREATE OR REPLACE TRIGGER TR_SERIE_SUPPLIER  BEFORE INSERT ON SERIE_SUPPLIER FOR EACH ROW
 
BEGIN
SELECT SEQ_SERIE_SUPPLIER.NEXTVAL INTO :NEW.SERIE_SUPPLIER_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_SERIE_SUPPLIER2
prompt ===================================
prompt
CREATE OR REPLACE TRIGGER TR_SERIE_SUPPLIER2  BEFORE INSERT ON SERIE_SUPPLIER2 FOR EACH ROW
 
BEGIN
SELECT SEQ_SERIE_SUPPLIER2.NEXTVAL INTO :NEW.SERIE_SUPPLIER2_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_SERINOTE
prompt ============================
prompt
CREATE OR REPLACE TRIGGER TR_SERINOTE  BEFORE INSERT ON SERINOTE FOR EACH ROW
 
BEGIN
SELECT SEQ_SERINOTE.NEXTVAL INTO :NEW.SERINOTE_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_SETUPTYPE
prompt =============================
prompt
CREATE OR REPLACE TRIGGER TR_SETUPTYPE  BEFORE INSERT ON SETUPTYPE FOR EACH ROW
 
BEGIN
SELECT SEQ_SETUPTYPE.NEXTVAL INTO :NEW.SETUPTYPE_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_SUPPLIER
prompt ============================
prompt
CREATE OR REPLACE TRIGGER TR_SUPPLIER  BEFORE INSERT ON SUPPLIER FOR EACH ROW
 
BEGIN
SELECT SEQ_SUPPLIER.NEXTVAL INTO :NEW.SUPPLIER_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_SYSMESSAGE
prompt ==============================
prompt
CREATE OR REPLACE TRIGGER TR_SYSMESSAGE  BEFORE INSERT ON SYSMESSAGE FOR EACH ROW
 
BEGIN
SELECT SEQ_SYSMESSAGE.NEXTVAL INTO :NEW.SYSMESSAGE_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_TIMENOTE
prompt ============================
prompt
CREATE OR REPLACE TRIGGER TR_TIMENOTE  BEFORE INSERT ON TIMENOTE FOR EACH ROW
 
BEGIN
SELECT SEQ_TIMENOTE.NEXTVAL INTO :NEW.TIMENOTE_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_TRF
prompt =======================
prompt
CREATE OR REPLACE TRIGGER TR_TRF  BEFORE INSERT ON TRF FOR EACH ROW
 
BEGIN
SELECT SEQ_TRF.NEXTVAL INTO :NEW.TRF_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_TYPENOTE
prompt ============================
prompt
CREATE OR REPLACE TRIGGER TR_TYPENOTE  BEFORE INSERT ON TYPENOTE FOR EACH ROW
 
BEGIN
SELECT SEQ_TYPENOTE.NEXTVAL INTO :NEW.TYPENOTE_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_TYPE_SEQUENCE
prompt =================================
prompt
CREATE OR REPLACE TRIGGER TR_TYPE_SEQUENCE  BEFORE INSERT ON TYPE_SEQUENCE FOR EACH ROW
 
BEGIN
SELECT SEQ_TYPE_SEQUENCE.NEXTVAL INTO :NEW.TYPE_SEQUENCE_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_TYPE_STOCK
prompt ==============================
prompt
CREATE OR REPLACE TRIGGER TR_TYPE_STOCK  BEFORE INSERT ON TYPE_STOCK FOR EACH ROW
 
BEGIN
SELECT SEQ_TYPE_STOCK.NEXTVAL INTO :NEW.TYPE_STOCK_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_USER_
prompt =========================
prompt
CREATE OR REPLACE TRIGGER TR_USER_  BEFORE INSERT ON USER_ FOR EACH ROW
 
BEGIN
SELECT SEQ_USER_.NEXTVAL INTO :NEW.USER__EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_USER_DATA
prompt =============================
prompt
CREATE OR REPLACE TRIGGER TR_USER_DATA  BEFORE INSERT ON USER_DATA FOR EACH ROW
 
BEGIN
SELECT SEQ_USER_DATA.NEXTVAL INTO :NEW.USER_DATA_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_USER_LICENSE
prompt ================================
prompt
CREATE OR REPLACE TRIGGER TR_USER_LICENSE  BEFORE INSERT ON USER_LICENSE FOR EACH ROW
 
BEGIN
SELECT SEQ_USER_LICENSE.NEXTVAL INTO :NEW.USER_LICENSE_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_USER_SEL
prompt ============================
prompt
CREATE OR REPLACE TRIGGER TR_USER_SEL  BEFORE INSERT ON USER_SEL FOR EACH ROW
 
BEGIN
SELECT SEQ_USER_SEL.NEXTVAL INTO :NEW.USER_SEL_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_USER_XMLDATA
prompt ================================
prompt
CREATE OR REPLACE TRIGGER TR_USER_XMLDATA  BEFORE INSERT ON USER_XMLDATA FOR EACH ROW
 
BEGIN
SELECT SEQ_USER_XMLDATA.NEXTVAL INTO :NEW.USER_XMLDATA_EM_ADDR FROM  DUAL;
END;
/

prompt
prompt Creating trigger TR_VCT
prompt =======================
prompt
CREATE OR REPLACE TRIGGER TR_VCT  BEFORE INSERT ON VCT FOR EACH ROW
 
BEGIN
SELECT SEQ_VCT.NEXTVAL INTO :NEW.VCT_EM_ADDR FROM  DUAL;
END;
/