create or replace view v_detailnodewithtimeseries as
select p.pvt_em_addr detailnodeid,
       t.timeseriesid,
       year,
       m1,
       m2,
       m3,
       m4,
       m5,
       m6,
       m7,
       m8,
       m9,
       m10,
       m11,
       m12,
       m13,
       m14
  from pvt p,
       (select r.pvt17_em_addr detailnodeid,
               r.num_serie timeseriesid,
               d.annee year,
               f_Convert_1E20(d.m_1) m1,
               f_Convert_1E20(d.m_2) m2,
               f_Convert_1E20(d.m_3) m3,
               f_Convert_1E20(d.m_4) m4,
               f_Convert_1E20(d.m_5) m5,
               f_Convert_1E20(d.m_6) m6,
               f_Convert_1E20(d.m_7) m7,
               f_Convert_1E20(d.m_8) m8,
               f_Convert_1E20(d.m_9) m9,
               f_Convert_1E20(m_10) m10,
               f_Convert_1E20(d.m_11) m11,
               f_Convert_1E20(d.m_12) m12,
               f_Convert_1E20(d.m_13) m13,
               f_Convert_1E20(d.m_14) m14
          from don d, rpd r
         where d.rpd18_em_addr = r.rpd_em_addr) t
 where p.pvt_em_addr = t.detailnodeid(+);
