create or replace view v_tradechannelvalues as
select ID,
       C49,
       C50,
       C51,
       C52,
       C53,
       C54,
       C55,
       C56,
       C57,
       C58,
       C59,
       C60,
       C61,
       C62,
       C63,
       C64,
       C65,
       C66,
       C67
  from (select r.dis9_em_addr id, v.num_crt, v.val
          from rfc r, vct v
         where r.ident_crt = 68
           and r.vct10_em_addr = v.vct_em_addr) pivot(max(val) for num_crt in(49 as c49,
                                                                              50 as c50,
                                                                              51 as c51,
                                                                              52 as c52,
                                                                              53 as c53,
                                                                              54 as c54,
                                                                              55 as c55,
                                                                              56 as c56,
                                                                              57 as c57,
                                                                              58 as c58,
                                                                              59 as c59,
                                                                              60 as c60,
                                                                              61 as c61,
                                                                              62 as c62,
                                                                              63 as c63,
                                                                              64 as c64,
                                                                              65 as c65,
                                                                              66 as c66,
                                                                              67 as c67));
